export const seasons = [
  [
    "2004–05",
    "Barcelona",
    "The beginning",
    "Debut at 17. First senior goal, assisted by Ronaldinho.",
    9,
    1,
    0,
    "La Liga",
  ],
  [
    "2005–06",
    "Barcelona",
    "European champion",
    "From youth world champion to his first Champions League medal.",
    25,
    8,
    3,
    "Champions League",
  ],
  [
    "2006–07",
    "Barcelona",
    "A star arrives",
    "A Clásico hat-trick and that Getafe goal.",
    36,
    17,
    3,
    "Spanish Super Cup",
  ],
  [
    "2007–08",
    "Barcelona",
    "The new number ten",
    "Olympic gold followed; a changing of the guard at Barça.",
    40,
    16,
    13,
    "—",
  ],
  [
    "2008–09",
    "Barcelona",
    "The treble",
    "Guardiola, Rome and a header no one saw coming.",
    51,
    38,
    17,
    "Treble",
  ],
  [
    "2009–10",
    "Barcelona",
    "First Ballon d’Or",
    "A 47-goal season and the world’s best player crown.",
    53,
    47,
    12,
    "La Liga",
  ],
  [
    "2010–11",
    "Barcelona",
    "Peak Barcelona",
    "Wembley brilliance in one of football’s greatest sides.",
    55,
    53,
    23,
    "Champions League",
  ],
  [
    "2011–12",
    "Barcelona",
    "The 73",
    "A record-breaking club season; four goals in one UCL match.",
    60,
    73,
    29,
    "Copa del Rey",
  ],
  [
    "2012–13",
    "Barcelona",
    "91 in a year",
    "A fourth straight Ballon d’Or and a 100-point league title.",
    50,
    60,
    15,
    "La Liga",
  ],
  [
    "2013–14",
    "Barcelona",
    "The difficult year",
    "Injury interruptions and a World Cup final on the horizon.",
    46,
    41,
    14,
    "Spanish Super Cup",
  ],
  [
    "2014–15",
    "Barcelona",
    "MSN & the treble",
    "That Bayern semi-final, Berlin, and a second treble.",
    57,
    58,
    27,
    "Treble",
  ],
  [
    "2015–16",
    "Barcelona",
    "Domestic double",
    "A fifth Ballon d’Or and another league-and-cup double.",
    49,
    41,
    23,
    "La Liga · Copa del Rey",
  ],
  [
    "2016–17",
    "Barcelona",
    "500 at the Bernabéu",
    "The shirt celebration became an instant icon.",
    52,
    54,
    20,
    "Copa del Rey",
  ],
  [
    "2017–18",
    "Barcelona",
    "Domestic dominance",
    "Unbeaten almost all season; Golden Shoe number five.",
    54,
    45,
    18,
    "La Liga · Copa del Rey",
  ],
  [
    "2018–19",
    "Barcelona",
    "Captain",
    "His first season as captain; the impossible Liverpool free-kick.",
    50,
    51,
    22,
    "La Liga",
  ],
  [
    "2019–20",
    "Barcelona",
    "The assist king",
    "A record 21 league assists in a turbulent season.",
    44,
    31,
    27,
    "—",
  ],
  [
    "2020–21",
    "Barcelona",
    "The farewell season",
    "A last Copa del Rey and finally, Copa América with Argentina.",
    47,
    38,
    14,
    "Copa del Rey · Copa América",
  ],
  [
    "2021–22",
    "Paris Saint-Germain",
    "Paris, year one",
    "A new club after 21 years; league champion in France.",
    34,
    11,
    14,
    "Ligue 1",
  ],
  [
    "2022–23",
    "Paris Saint-Germain",
    "Immortal",
    "Seven goals in Qatar, the World Cup, and an eighth Ballon d’Or.",
    41,
    21,
    20,
    "World Cup · Ligue 1",
  ],
  [
    "2023",
    "Inter Miami",
    "Miami magic",
    "A debut free-kick and seven wins to the club’s first trophy.",
    14,
    11,
    5,
    "Leagues Cup",
  ],
  [
    "2024",
    "Inter Miami",
    "Record breakers",
    "A record MLS regular season and the Supporters’ Shield.",
    25,
    23,
    13,
    "Supporters’ Shield",
  ],
  [
    "2025",
    "Inter Miami",
    "Champions of MLS",
    "A Golden Boot season finished with Miami’s first MLS Cup.",
    null,
    null,
    null,
    "MLS Cup",
  ],
  [
    "2026",
    "Inter Miami",
    "Still writing it",
    "At 39, the captain’s final chapters are being written in real time.",
    null,
    null,
    null,
    "In progress",
  ],
].map((s, i) => ({
  id: i,
  season: s[0],
  club: s[1],
  title: s[2],
  story: s[3],
  apps: s[4],
  goals: s[5],
  assists: s[6],
  honours: s[7],
}));

export const seasonStories = {
  "2004–05": {
    title: "The first light",
    dek: "A borrowed shirt number, nine senior appearances and the little left-footed chip that quietly opened football’s next great age.",
    paragraphs: [
      "There are beginnings that arrive with brass bands, and beginnings that slip into view almost apologetically. Lionel Messi’s first senior season belonged to the latter kind. Barcelona in the summer of 2004 were not waiting for a saviour. For once, they believed they had already found their way. Frank Rijkaard’s first year had ended in a great rush of confidence, Joan Laporta’s presidency had restored ambition, and Ronaldinho had returned delight to a stadium that had spent too many seasons peering anxiously towards Madrid. Samuel Eto’o, Deco, Ludovic Giuly, Juliano Belletti and Henrik Larsson arrived to deepen the revival. Somewhere beneath all that noise was a 17-year-old in the number 30 shirt: slight, watchful, still dividing his days between youth football, Barça B and occasional invitations to train among famous men.",
      "The first hint came in July, in a modest pre-season match at Palamós. Messi scored in a 6–0 victory, an unofficial goal in a fixture that seemed destined to live only in old team sheets and the memories of those who happened to be there. Yet it established the essential grammar early: the low centre of gravity, the ball kept unusually close, the left foot making difficult things appear prearranged. Rijkaard did not hurry him. Barcelona had Giuly on the right, Ronaldinho drifting in from the left and Eto’o attacking the centre with the impatience of a man determined to prove a point. A teenager could be protected inside such abundance. He could watch, learn and wait.",
      "October brought the call. On the 16th, Barcelona crossed the city to Montjuïc for the derby against Espanyol. It was a hard, narrow evening rather than a gala. Deco’s deflected goal had given Barça the lead; Andrés Iniesta had already entered from the bench. With eight minutes remaining, Rijkaard withdrew Deco and sent on Messi. He was 17 years and 114 days old, wearing 30, his hair long and his expression almost stern. There was no goal, no outrageous dribble to announce the future. There were simply a few composed touches in a 1–0 victory and the unmistakable fact of his presence. The senior career had begun in the same Olympic stadium where, nearly two decades later, Barcelona would temporarily make their home.",
      "Eleven days later came a less romantic lesson. Away to third-tier Gramenet in the Copa del Rey, Messi started while many of the established stars were absent. The artificial surface was slick with rain, Barcelona never found their rhythm, and the tie stretched into extra time before Gramenet won 1–0. It was the old cruelty of the cup: pedigree made irrelevant by a single awkward night. For Messi, it was valuable exposure to the unglamorous edge of senior football—the cramped spaces, the heavy challenges, the opponent whose entire season seemed to be concentrated into one evening. Great careers are remembered through finals and floodlights, but they are also educated on nights like Santa Coloma.",
      "By December, Barcelona had already qualified from their Champions League group when Rijkaard took a youthful side to Donetsk. Ronaldinho, Deco and Eto’o were left out; Messi, Joan Verdú and Francisco Peral received their first European starts. Shakhtar won 2–0 through two Julius Aghahowa goals, yet the result has become a footnote to the team sheet. Messi was now a Champions League footballer. He was still physically unfinished and not yet the player who would turn European knockout rounds into his private theatre, but the habits were visible: receiving under pressure, turning towards danger rather than away from it, treating the ball as shelter. Europe did not yet know what had entered the competition.",
      "The winter asked for patience. Barcelona’s season gathered authority through the established constellation around him. Xavi was growing into a freer, more influential midfield role; Deco supplied bite as well as invention; Ronaldinho conducted the mood of the city; Eto’o scored with a forward’s fury. Messi returned repeatedly to the reserves and waited through stretches when a first-team appearance amounted to a late handful of minutes. That waiting matters. Retrospect is tempted to make genius look inevitable, as though the doors simply opened in sequence. In reality, his seven league appearances that season totalled only 77 minutes. He was a possibility being managed, not yet a protagonist.",
      "Spring tightened the title race. Barcelona had led with style, but Real Madrid applied pressure and won April’s Clásico 4–2 at the Bernabéu. Rijkaard’s team could feel six trophyless years pressing against their shoulders. Messi reappeared in the league at Getafe on 17 April and, two weeks later, Albacete came to the Camp Nou. The match was still only 1–0 when he replaced Eto’o late on. Ronaldinho saw the run and lifted a pass over the defence; Messi met it with a left-footed lob so delicate that it seemed to pause above goalkeeper Raúl Valbuena. The flag went up. Offside. Most teenagers might have accepted the warning and chosen something safer next time.",
      "Messi and Ronaldinho simply repeated the idea. Another scooped pass, another dart behind the line, another lob—this one higher, cleaner and legal. The ball fell into the net in stoppage time for 2–0. Messi was 17 years and 311 days old, then Barcelona’s youngest league scorer. What survives most vividly is not merely the finish but the celebration: Ronaldinho bending so the boy could climb onto his back, both of them laughing beneath the Camp Nou lights. It has since acquired the symbolism of a handover, though life is rarely arranged so neatly. Ronaldinho remained the reigning joy of Barcelona. Messi had scored one senior goal. Still, football occasionally composes an image whose meaning grows with every passing year.",
      "A fortnight later, a 1–1 draw at Levante secured Barcelona’s seventeenth league title with two matches remaining—the club’s first championship in six years. Eto’o scored the equaliser; Rijkaard’s collective had completed the restoration. Messi’s statistical contribution was tiny: nine competitive appearances, one goal, scarcely enough playing time to fill a full match in La Liga. Yet the season feels larger than those numbers because every later wonder contains a trace of this first one. The disguised pass from Ronaldinho, the curved run, the refusal to be discouraged by the flag, the left foot lifting the ball beyond a goalkeeper: the vocabulary was already there.",
      "That summer, Messi travelled with Argentina to the World Youth Championship and returned a champion, but that belongs to the threshold of the next chapter. The 2004–05 season should be left where it ended: Barcelona restored to the summit, Ronaldinho smiling, Rijkaard vindicated, and a shy teenager standing just inside the first-team door. Nobody could reasonably have foreseen 778 Barcelona appearances or the mountain of goals and trophies to come. They only knew that the small number 30 made the stadium lean forward. Sometimes that is how history first announces itself—not with certainty, but with curiosity, a murmur spreading around the bowl, and the sense that you had better keep watching.",
    ],
    sources: [
      ["FC Barcelona: Messi’s official debut", "https://www.fcbarcelona.com/en/football/first-team/news/4147765/20-years-since-leo-messis-fc-barcelona-debut"],
      ["UEFA: Champions League debut in Donetsk", "https://www.uefa.com/uefachampionsleague/news/025a-0eaa7d66b33d-3b189c94306f-1000--aghahowa-earns-shakhtar-consolation/"],
      ["FC Barcelona: the first official goal", "https://www.fcbarcelona.com/en/football/first-team/news/4256638/20-years-since-leo-messis-first-official-goal/featured"],
      ["UEFA: Barcelona’s 2004–05 title", "https://www.uefa.com/news-media/news/01a9-0e6cc71410f2-1f8842b7df25-1000--team-ethic-fires-barca-to-glory/"],
    ],
    photos: [
      {
        after: 2,
        src: "https://www.fcbarcelona.com/fcbarcelona/photo/2024/10/12/9251c732-0b4a-4d08-b980-fe7f486fb972/2004-10-16-MESSI-06.JPG",
        alt: "Seventeen-year-old Lionel Messi in Barcelona's 2004–05 shirt during his official debut against Espanyol",
        caption: "The first official steps — Messi enters the Barcelona derby at Montjuïc, 16 October 2004.",
        credit: "FC Barcelona archive",
        href: "https://www.fcbarcelona.com/en/football/first-team/news/4147765/20-years-since-leo-messis-fc-barcelona-debut",
      },
    ],
    videos: [
      {
        after: 7,
        youtubeId: "j9ihJMqZGD0",
        title: "Messi's first official goal for FC Barcelona",
        caption: "Watch the move twice: the first lob ruled out, then Ronaldinho and Messi composing it all over again.",
        credit: "FC Barcelona",
        href: "https://www.youtube.com/watch?v=j9ihJMqZGD0",
      },
    ],
  },
  "2005–06": {
    title: "The world leans closer",
    dek: "A summer coronation, a passport, a Bernabéu education and the wet London night when Europe discovered that Barcelona’s quiet boy could bend its grandest matches around him.",
    paragraphs: [
      "The murmur followed him north that summer, from Barcelona to the Netherlands. Lionel Messi had ended his first senior season as a curiosity: the small number 30 who made the Camp Nou lean forward. He returned from the World Youth Championship carrying something heavier than promise. Argentina lost their opening match to the United States with Messi initially left on the bench, and the omission soon looked like one of those useful mistakes from which a tournament discovers its true shape. Introduced at half-time, he could not rescue the result, but thereafter Francisco Ferraro gave him freedom between midfield and attack. Messi scored against Egypt, helped settle Germany, then found the net in every knockout round. Against Brazil in the semi-final he drove a left-footed shot into the corner and created the winner; against Nigeria in Utrecht on 2 July, two calmly taken penalties secured a 2–1 victory. Six goals brought the Golden Boot. The Golden Ball confirmed what the matches had already said: he had arrived as the competition’s best player.",
      "He came back to Catalonia an under-20 world champion and, almost at once, football reminded him that ascent is rarely a clean line. On 17 August, José Pékerman sent him on for his senior Argentina debut against Hungary in Budapest. Messi gathered the ball, resisted Vilmos Vanczák’s tug and swung an arm backwards as he tried to escape. The referee produced a red card. His first international lasted scarcely a minute. He sat in the dressing room distraught, a young man who had travelled from a world title to expulsion in the space of six weeks. Yet seven days later came the Joan Gamper Trophy against Fabio Capello’s Juventus, and with it a truer glimpse of the season ahead. Messi tormented an accomplished defence with changes of direction too abrupt for the eye, let alone the marker. Capello asked Rijkaard whether Juventus might borrow him. The Camp Nou’s curiosity became possession: this one, they understood, must not be allowed to leave.",
      "For a while, paperwork threatened what defenders could not. Barcelona’s three non-European places were occupied and Messi’s eligibility became entangled in arguments over whether his earlier appearances had been properly registered. A loan to Cádiz was considered. He trained, waited and watched the league begin without him. Spanish citizenship, granted on 26 September, finally cleared the path. The delay now feels bureaucratic to the point of comedy, but at the time it placed a real uncertainty around a career still fragile enough to be redirected. Rijkaard’s patience mattered. So did the club’s decision after the Gamper: the teenager would remain close to Ronaldinho, Eto’o, Deco and Xavi, learning the rhythms of a side no longer content merely to be restored. Barcelona wanted to rule.",
      "His first league appearance of the campaign came at home to Zaragoza on 1 October. The minutes were beginning to gather, and so was trust. On 2 November Panathinaikos came to Barcelona in the Champions League. Messi started on the right, scored Barça’s third in a 5–0 win and looked entirely at home among Europe’s lights. The finish carried some of the old audacity: he pressed the goalkeeper, collected the loose ball, lifted it over him and headed into the empty net. It was his first European goal. At eighteen, he celebrated less like a boy surprised to be there than a forward irritated that the opening had taken so long to appear.",
      "Seventeen days later came the Bernabéu. Real Madrid against Barcelona can make experienced players shrink into the occasion, but Messi started as though the stadium were simply another patch of grass. He moved in from the right, combined with Ronaldinho and helped create the opening for Eto’o. Barcelona won 3–0; Ronaldinho scored twice and received that rarest tribute, applause from portions of the Madrid crowd. The evening belonged to the Brazilian’s grandeur, as it should have, but there was tenderness in the arrangement. Ronaldinho drew the room towards him; Messi slipped through the spaces the attention left behind. One was the reigning Ballon d’Or, playing with a smile broad enough to warm a hostile stadium. The other was still learning how little hostility could disturb him.",
      "By winter, Messi was no decorative prodigy. He appeared in ten consecutive league matches between December and February and finished the season with eight goals in 25 club appearances. Those figures are modest only when read backwards through the impossible standards he later established. In their own moment they described a teenager forcing his way into the best attacking side in Europe. Rijkaard could still select Giuly for balance and experience, but Messi altered the temperature of games. He received the ball facing two defenders and made the possibility of beating both seem not reckless but logical. Barcelona’s football had speed, structure and celebrity; the boy gave it suspense.",
      "Then, on 22 February, came Stamford Bridge. Rain had soaked the pitch until the surface looked almost black, and the Champions League rivalry between Chelsea and Barcelona already carried a season’s worth of resentment. José Mourinho’s English champions were powerful, organised and convinced of their own hard edge. Messi was 18 years, seven months and 28 days old. He played as though the argument had been arranged for him. From the right he attacked Asier del Horno repeatedly, rolling the ball under his left foot, stopping, accelerating, inviting contact and surviving it. He struck Petr Čech’s crossbar with a curling shot. In the 37th minute Del Horno flew into him near the touchline; both players rose, then the defender was shown red. Chelsea protested, Mourinho raged, but the deeper truth of the night was beyond the card. An elite European defence had treated an eighteen-year-old as the emergency around which everything else had to be reorganised.",
      "Barcelona won 2–1 after John Terry’s own goal and Eto’o’s late header, but scorelines preserve only the skeleton of certain matches. The flesh of this one was Messi’s nerve. The mud did not slow him; the noise did not hurry him. Every time he received possession, Stamford Bridge made that involuntary sound reserved for danger recognised a fraction too late. This was the point at which the private knowledge of teammates, youth coaches and regular Camp Nou watchers became continental knowledge. Europe had seen gifted teenagers before. What unsettled Chelsea was the authority: the sense that Messi was not sampling the level but measuring it, discovering that the grandest club competition could be made to move at his pace.",
      "The return leg supplied the season’s cruelty. After 25 minutes at the Camp Nou, Messi felt pain in his right thigh and had to leave. Barcelona completed the tie, then removed Benfica and Milan, while he rehabilitated first in Catalonia and later in Argentina. Each optimistic return date receded. On 17 May, Barça met Arsenal at the Stade de France without him. Jens Lehmann was sent off, Sol Campbell put Arsenal ahead, and late goals from Eto’o and Juliano Belletti delivered Barcelona’s second European Cup. Messi had played six matches in the campaign and owned the medal honestly, but he was not dressed to enter the final and the celebration could not feel whole. At eighteen he learned one of football’s more adult sorrows: a team can achieve the thing you desire most while your own body leaves you stranded just outside the picture.",
      "There was La Liga too, retained with room to spare, and there was a World Cup waiting in Germany once his thigh recovered. But the shape of 2005–06 is clearest between Utrecht, London and Paris. In Utrecht he became a champion in his own right. In London he became a European event. In Paris he became, painfully, an observer of the summit he had helped his club reach. The boy who began the year needing permission to play ended it with Spain, Argentina and the Champions League all debating how much space to give him. The answer, already, was none; the problem was that none did not appear to be enough. Barcelona had won Europe without Messi in the final. The next chapter would ask a more dangerous question: what might happen when the great matches were finally his from beginning to end?",
    ],
    sources: [
      ["FIFA: Messi at the 2005 U-20 World Cup", "https://www.fifa.com/en/tournaments/mens/u20worldcup/chile-2025/articles/lionel-messi-u20-world-cup"],
      ["FIFA: Messi’s senior Argentina debut", "https://www.fifa.com/en/articles/lionel-messi-international-debut-anniversary"],
      ["FC Barcelona: the 2005 Gamper against Juventus", "https://www.fcbarcelona.com/en/football/first-team/noticias/1645854/revive-el-barca-juventus-del-2005/featured"],
      ["FC Barcelona: Messi’s first European goal", "https://www.fcbarcelona.com/en/news/738017/messi-reaches-100-goals-in-european-competition"],
      ["FC Barcelona: Messi’s Stamford Bridge exhibition", "https://www.fcbarcelona.com/en/news/728288/lionel-messis-exhibition-at-stamford-bridge-in-2006"],
      ["UEFA: Barcelona win at Stamford Bridge", "https://www.uefa.com/uefachampionsleague/news/01b2-0ea84402772a-2a1f5cdac8b3-1000--eto-o-winner-gives-barca-the-edge/"],
      ["UEFA: the thigh injury that ended Messi’s European campaign", "https://www.uefa.com/uefachampionsleague/news/01b3-0e6d6ef31aa1-ecd435604ce1-1000--messi-to-miss-last-eight-date/"],
    ],
    photos: [
      {
        after: 1,
        src: "https://estaticos-cdn.prensaiberica.es/clip/47325e52-ba91-4ff7-8be2-4db80b713790_16-9-discover-aspect-ratio_default_0.jpg",
        alt: "Lionel Messi evades Patrick Vieira during Barcelona's 2005 Joan Gamper Trophy match against Juventus",
        caption: "The night Capello asked about him — Messi escapes Patrick Vieira at the Camp Nou, 24 August 2005.",
        credit: "SPORT",
        href: "https://www.sport.es/es/noticias/45-aniversario/gamper-2005-eclosion-messi-107222621",
      },
      {
        after: 5,
        src: "https://www.fcbarcelona.com/fcbarcelona/photo/2018/06/15/801d2bf4-4673-46c1-a279-48d0b94159f0/axsOeYXF.jpg",
        alt: "Lionel Messi carries the ball for Barcelona against Chelsea at Stamford Bridge",
        caption: "Europe takes notice — Messi drives at Chelsea beneath the Stamford Bridge lights, 22 February 2006.",
        credit: "FC Barcelona archive",
        href: "https://www.fcbarcelona.com/en/news/728288/lionel-messis-exhibition-at-stamford-bridge-in-2006",
      },
    ],
    videos: [
      {
        after: 7,
        youtubeId: "KSMZ_ghfWfo",
        title: "Messi vs Chelsea — Stamford Bridge, 2006",
        caption: "The chapter’s turning point in full: Messi’s first great European night, 22 February 2006.",
        credit: "MM Comps",
        href: "https://www.youtube.com/watch?v=KSMZ_ghfWfo",
      },
    ],
  },
  "2006–07": {
    title: "The match belongs to him",
    dek: "A broken foot, a Clásico hat-trick, a goal borrowed from Maradona—and the season when Messi became inevitable even as Barcelona’s certainty began to fray.",
    paragraphs: [
      "Germany offered Lionel Messi his first sight of football’s largest stage and, like so much of his early career, only a partial invitation to occupy it. He arrived at the 2006 World Cup newly fit, the thigh injury that had kept him from Barcelona’s European final still close enough to make every sprint an examination. Against Serbia and Montenegro in Gelsenkirchen on 16 June, José Pékerman sent him on after 74 minutes with Argentina already in command. Messi created a goal for Hernán Crespo, then scored one himself in the 88th minute, sliding the ball beneath Dragoslav Jevrić to complete a 6–0 victory. He was eighteen, the youngest Argentine to play and score at a World Cup. Yet when the quarter-final against Germany tightened into extra time and penalties, he remained on the bench. Argentina went out. The tournament gave him a goal, an assist and an early understanding that talent does not always receive the minutes it believes it can transform.",
      "Back in Barcelona, the number on his shorts changed from 30 to 19. It was a small promotion, halfway towards the shirt that would eventually become inseparable from him. Barça began as champions of Spain and Europe, with Ronaldinho still football’s most magnetic figure and Rijkaard’s team expected to extend its reign. They beat Espanyol over two legs to win the Spanish Super Cup, but Sevilla dismantled them 3–0 in the UEFA Super Cup in Monaco. The result felt like an August correction rather than a warning. Great teams are granted that indulgence: every defeat is called an exception until enough exceptions gather to form a pattern.",
      "Messi began the autumn with increasing authority on the right. Samuel Eto’o’s serious knee injury in September removed the attack’s sharpest central blade, placing more responsibility on Ronaldinho and the nineteen-year-old beside him. Chelsea met Barcelona again in Europe. At Stamford Bridge, Messi was once more the visitor carrying the clearest threat even as Didier Drogba won the match for José Mourinho’s side; at the Camp Nou he combined sharply with Gianluca Zambrotta and Ronaldinho before Drogba’s stoppage-time equaliser turned victory into a 2–2 draw. Barcelona were still recognisably themselves—possession, width, Deco’s abrasion, Xavi’s intelligence—but their command had become less serene. Messi’s directness increasingly served as the way through when the collective route narrowed.",
      "On 12 November, against Zaragoza, his left foot betrayed him. There was no operatic collision, only Messi sitting on the grass, removing his boot and recognising that something inside it was wrong. Barcelona later confirmed a fracture of the fifth metatarsal. Surgery followed; the estimate was three months. He missed the decisive Champions League group matches and the Club World Cup in Japan, where Barça lost the final to Internacional. Injury had already taken Paris from him. Now, just as he was becoming essential rather than promising, another campaign broke into a before and an after. Rehabilitation is the least visible part of a footballer’s life: empty pitches, repeated movements, progress measured in degrees rather than goals. For Messi it also sharpened a recurring tension—the extraordinary freedom of his football housed inside a body still learning how to withstand it.",
      "He returned in February to a team whose margins had thinned. Liverpool came to the Camp Nou in the Champions League round of 16, fell behind to Deco and then won 2–1 through Craig Bellamy and John Arne Riise. At Anfield, Barcelona won the second leg 1–0 but departed on away goals. The European champions were out before the quarter-finals. Four days later Real Madrid arrived at the Camp Nou. The timing was cruel and therefore perfect: Barcelona bruised by elimination, Madrid gathering under Fabio Capello, the league balanced between rivals who did not entirely trust themselves. Messi had never scored in a Clásico. By the end of the night, he had scored three.",
      "Ruud van Nistelrooy put Madrid ahead after five minutes. Messi answered six minutes later, arriving from the right to meet Eto’o’s pass and driving left-footed across Iker Casillas. Van Nistelrooy restored the lead from the penalty spot; Messi equalised again, following Ronaldinho’s shot and hammering the rebound high into the net. Then Oleguer was dismissed before half-time, leaving Barcelona to play the second half with ten. Sergio Ramos headed Madrid in front for a third time with seventeen minutes remaining. The match seemed to be closing when Ronaldinho found Messi on the right in the final minute. He accelerated inside Iván Helguera, held off a desperate challenge and struck across Casillas into the far corner. The Camp Nou did not so much celebrate as detonate.",
      "What followed supplied the portrait. Messi ran towards the crowd, pulled up the Barcelona shirt and revealed a white vest marked ‘TÍO’ — a dedication to his uncle and godfather, whose father had died the previous day. He had scored his first senior hat-trick against Real Madrid, rescuing a 3–3 draw while his team played a man short. The goals mattered, but so did their variety: timing for the first, violence for the second, composure under exhaustion for the third. This was no longer a gifted young player decorating a great side. When the great side was vulnerable, the match had migrated towards him. Ronaldinho remained the reigning Ballon d’Or holder; Eto’o remained the elite striker. Yet the final demand of the evening belonged to Messi, and he answered it as though football had merely returned something that was already his.",
      "Thirty-nine days later, Getafe came to the Camp Nou for the first leg of a Copa del Rey semi-final. Barcelona led 1–0 when Xavi passed to Messi near the right touchline inside his own half. Two defenders approached. He slipped between them, the second beaten through the legs, and crossed halfway with open grass ahead. Each subsequent touch seemed both improvised and exact. He moved inside Alexis, escaped Belenguer, entered the penalty area, rounded goalkeeper Luis García and finished from a narrowing angle. Twelve seconds, roughly sixty metres, five opponents. The resemblance to Diego Maradona’s 1986 goal against England was not something editors had to manufacture; it announced itself before the ball reached the net. The same country, the same low-running silhouette, the same left foot carrying the ball through a defence that dissolved one man at a time.",
      "Comparison can be a burden, particularly in Argentina, where Maradona was less a former player than a national language. Messi’s goal did not settle that conversation; nothing ever would. What it established was that imitation was too small a word. He had not reconstructed an old masterpiece deliberately. He had seen the same succession of problems and solved them through the same rare geometry. Barcelona won 5–2, Messi scored twice, and the tie appeared finished. Three weeks later Getafe won the return 4–0. The scorer of the season’s most celebrated goal would not play in the Copa final. Beauty had provided no immunity from consequence.",
      "La Liga supplied the final cruelty. Barcelona and Real Madrid entered June inseparable, but Madrid held the head-to-head advantage. On the penultimate weekend, Barça led Espanyol 2–1 while Madrid trailed Zaragoza by the same score. In the 89th minute, almost simultaneously, Raúl Tamudo equalised at the Camp Nou and Van Nistelrooy equalised at La Romareda. Two late goals, in different cities, shifted the championship back towards Madrid. On the final day Barça overwhelmed Gimnàstic 5–1 and Messi scored twice. It did not matter. Madrid recovered from 1–0 down against Mallorca to win 3–1 and took the title with both clubs on 76 points. Barcelona had scored more, conceded fewer and lost fewer matches. The table still placed them second.",
      "Messi ended the club season with 17 goals in 36 appearances, plus the Spanish Super Cup, the Bravo Award and another FIFPRO Young Player prize. Those honours describe only the surface. The deeper change was one of status. A year earlier, Europe had discovered him at Stamford Bridge. Now Barcelona had discovered the feeling of needing him. The broken metatarsal divided his season, but after returning he produced the first Clásico hat-trick by a Barcelona player since Romário and a goal destined to survive every retelling. The team around him was beginning to lose its old equilibrium; fame, injury and fatigue had entered Rijkaard’s dressing room. Messi did not rescue the trophies. He did something more important for the longer story: he showed that when the structure weakened, he could become the structure.",
    ],
    sources: [
      ["FIFA: Messi’s first World Cup goal", "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/lionel-messi-top-10-moments"],
      ["UEFA: the fractured metatarsal", "https://www.uefa.com/uefachampionsleague/news/01bb-0e6dbbc803c2-5025d4c6cbf0-1000--messi-out-as-barca-injuries-mount/"],
      ["UEFA: Liverpool win at the Camp Nou", "https://www.uefa.com/uefachampionsleague/news/01be-0e6e2c719dd8-25a0eb2ceed3-1000--liverpool-stun-holders-barca/"],
      ["UEFA: Messi’s Clásico treble", "https://www.uefa.com/news-media/news/01bf-0f84ac346042-9fef68775430-1000--messi-treble-saves-barcelona/"],
      ["FC Barcelona: Messi’s first hat-trick", "https://www.fcbarcelona.com/en/football/first-team/news/775153/10-years-since-leo-messis-first-barca-hat-trick"],
      ["FC Barcelona: the historic Getafe goal", "https://www.fcbarcelona.com/en/football/first-team/news/769781/10-years-since-messis-historic-goal-against-getafe"],
      ["FC Barcelona: 2006–07 season report", "https://media1.fcbarcelona.com/media/asset_publics/resources/000/006/563/original/MEMORIA_CLUB_CAST_06-07.v1321548223.pdf"],
      ["Mundo Deportivo: Messi’s dedication to his uncle", "https://www.mundodeportivo.com/futbol/fc-barcelona/barca-goles/20260315/1004152593/messi-estreno-real-madrid-hat-trick.html"],
    ],
    photos: [
      {
        after: -1,
        src: "https://img.asmedia.epimg.net/resizer/v2/HUIHLZ5S2NG4DESHYEWE7WJIUA.jpg?auth=19412f4db1b07986a9f91ba35f74d4848f5827ff31b58c1e8d6ead911e9ce5de&width=1472&height=828&focal=1798%2C972",
        alt: "Lionel Messi lifts his Barcelona shirt to reveal a white vest marked TÍO after his first Clásico hat-trick",
        caption: "A dedication to his uncle after completing his first Clásico hat-trick — Camp Nou, 10 March 2007.",
        credit: "Miguel Ruiz / FC Barcelona via AS",
        href: "https://as.com/us/futbol/lionel-messi-a-16-anos-de-su-primer-hat-trick-ante-real-madrid-n/",
      },
      {
        after: 7,
        src: "https://www.fcbarcelona.com/fcbarcelona/photo/2018/07/02/49f5ffdf-f822-479d-bbdf-0c827fd5f9e1/MFwoxQHO.jpg",
        alt: "Lionel Messi rounds Getafe goalkeeper Luis García during his famous solo goal",
        caption: "The run that revived Maradona’s ghost — Messi rounds Luis García against Getafe, 18 April 2007.",
        credit: "FC Barcelona archive",
        href: "https://www.fcbarcelona.com/en/football/first-team/news/769781/10-years-since-messis-historic-goal-against-getafe",
      },
    ],
    videos: [
      {
        after: 6,
        youtubeId: "VTHLvdM1sXU",
        title: "Messi’s first Barcelona hat-trick",
        caption: "Three replies to three Madrid leads: Messi’s first senior hat-trick, 10 March 2007.",
        credit: "FC Barcelona",
        href: "https://www.youtube.com/watch?v=VTHLvdM1sXU",
      },
    ],
  },
  "2007–08": {
    title: "The space he inherited",
    dek: "Sixteen goals, a recurring tear, an Old Trafford farewell and the Beijing summer in which Messi stepped out of a fading Barcelona age carrying gold.",
    paragraphs: [
      "Thierry Henry arrived in Barcelona in June 2007 with the aura of a man who had already completed one footballing life. He was Arsenal’s record scorer, a World Cup winner and the most glamorous addition imaginable to an attack that already contained Ronaldinho, Samuel Eto’o and Lionel Messi. The shorthand was irresistible: the Fantastic Four. It appeared less a forward line than an argument against competitive balance. Yet great collections of players are not always great teams, and Barcelona were attempting to add another room to a house whose foundations had begun to move. The league lost on head-to-head record, the collapse at Getafe, the habits gathering around Ronaldinho and Deco—none had disappeared during the summer. Frank Rijkaard’s side were richer in names than they had been a year earlier and poorer in certainty.",
      "Messi returned wearing 19 and no longer required an introduction. The Clásico hat-trick and the Getafe run had changed the terms. At twenty, he was not the academy boy granted minutes beside the stars; he was the player the Camp Nou watched when a match tightened. Barcelona began the league with a goalless draw at Racing Santander, but September offered the first sustained evidence of the new hierarchy. Against Lyon in Europe, Messi’s cross-shot forced François Clerc’s own goal and he later finished a flowing move with his right foot in a 3–0 win. Three nights later Sevilla came to the Camp Nou. Messi broke a scoreless match with a controlled volley from Henry’s clipped pass, then added a penalty soon afterwards. The stadium’s fiftieth anniversary belonged to its youngest headline act.",
      "There was still exhilaration in the old team. Ronaldinho could bend a match from a standing start, Eto’o remained ferocious when fit, Xavi and Andrés Iniesta were becoming the game’s most elegant shared intelligence, and the teenagers Bojan Krkić and Giovani dos Santos made the future appear unusually crowded. But the balance was fragile. Henry was learning the left side while carrying the memory of back trouble; Eto’o missed the early months after a thigh injury; Ronaldinho’s form and conditioning became public argument. Messi supplied the cleanest line through the noise. He scored away to Stuttgart in October, found six Champions League goals across the campaign, and played with the urgent, slaloming directness that made Barcelona look young whenever the rest of the side looked tired.",
      "That directness also exposed the body required to sustain it. On 15 December at Valencia, during a 3–0 league win, Messi tore the biceps femoris in his left thigh. UEFA’s prognosis was approximately four weeks out, removing him from the final match before Christmas, the Clásico at the Camp Nou. Madrid won 1–0 through Júlio Baptista. Without Messi, Barcelona possessed the ball but little incision; the defeat left them seven points behind the leaders. He returned in January, carefully at first, and by 20 February at Celtic Park looked liberated again. Celtic twice led in the Champions League round of 16. Messi twice equalised, the second a beautifully delayed exchange with Ronaldinho, before Henry’s curling finish completed a 3–2 victory. It was one of the season’s clearest glimpses of what this team had once been and what Messi might still make it.",
      "The return leg on 4 March lasted thirty-eight minutes for him. Chasing the ball in a sprint, Messi suffered another tear in his left thigh. There was no opponent to blame and no challenge to replay. He stopped, covered his face and left the pitch in tears, supported by a member of Barcelona’s staff. UEFA recorded a six-week absence. The injury took both Champions League quarter-finals against Schalke and the decisive Copa del Rey semi-final away to Valencia from him. Barcelona edged past Schalke without conceding, but Valencia won 3–2 at Mestalla and reached the cup final. By the time Messi could return, the league challenge had also begun to loosen beyond repair.",
      "Barcelona treated the recovery cautiously, understandably so: this was another muscular failure in a player whose acceleration asked extreme questions of his hamstrings. Messi came back on 12 April as a substitute against Recreativo and was ready to start eleven days later when Manchester United visited the Camp Nou. The European Cup had become Barcelona’s remaining route to salvation. Cristiano Ronaldo missed an early penalty, United retreated, and Barcelona spent the evening circling a defence marshalled by Rio Ferdinand. Messi’s bursts provided the electricity, but no finish. The first leg ended 0–0, a score that carried both possibility and menace to Manchester.",
      "Old Trafford on 29 April felt like an ending before anyone had officially announced one. Paul Scholes struck after fourteen minutes, punishing a loose clearance from Gianluca Zambrotta with a shot that swerved beyond Víctor Valdés from distance. Barcelona then needed one goal to reach the final. Again the ball searched for Messi. He moved inside Wes Brown, drew a save from Edwin van der Sar, escaped Scholes near the byline and kept returning to the dense red wall. Yet United defended the penalty area with the concentration Barcelona had misplaced across their domestic season. Henry and Bojan came from the bench. The equaliser did not. Messi had been the visitor most capable of altering the night, but capability and outcome had separated. United won the tie 1–0 and went on to become European champions.",
      "Eight days later Barcelona walked into the Santiago Bernabéu and formed a guard of honour for the newly crowned Spanish champions. The ritual was sporting; the symbolism was merciless. Madrid then won 4–1. Raúl, Arjen Robben, Gonzalo Higuaín and Ruud van Nistelrooy scored before Henry’s late consolation. Messi played the full match and kept trying to carry the ball through the humiliation, but the contrast could not be softened. Two years earlier Ronaldinho had received applause in this stadium after making Madrid look obsolete. Now he was absent, his Barcelona career effectively over, while the younger Argentine ran inside a team whose era had reached its visible end. Rijkaard’s departure was confirmed, and Pep Guardiola—one season into his coaching life with Barcelona B—was chosen to replace him.",
      "Barcelona finished third, eighteen points behind Madrid and ten behind Villarreal. They had won no trophy. Messi’s club totals—40 appearances and 16 goals in all competitions—were achieved despite the two left-thigh injuries, and no Barcelona player scored more often in Europe. Statistics alone cannot convey the handover. Ronaldinho was still the owner of the number 10, still the face printed across the previous age, but Messi had become the team’s emotional weather. When he accelerated, belief returned. When he broke down, the season appeared to break with him. The inheritance was not ceremonial. It arrived as responsibility inside a declining side.",
      "Then came a summer argument that would end in joy. Barcelona contested FIFA’s instruction to release Messi for the Beijing Olympic tournament because the club faced a Champions League qualifier. On 6 August the Court of Arbitration for Sport upheld Barcelona’s appeal, finding no legal obligation to release under-23 players because the Olympics were not on FIFA’s international calendar. The ruling gave the club the right to recall him. After Guardiola spoke with Messi, who made clear that he wanted to remain in Beijing, Barcelona chose not to exercise it. In China, Messi scored against Côte d’Ivoire, then opened the quarter-final against the Netherlands and helped create Ángel Di María’s extra-time winner. Argentina overwhelmed Brazil 3–0 in the semi-final. Against Nigeria at the Bird’s Nest on 23 August, Messi’s pass released Di María in the 58th minute; the winger’s lifted finish supplied the only goal and Argentina’s second successive Olympic title.",
      "The medal belonged to the summer after the club season, but it completes its meaning. Barcelona’s year had ended with an old order exhausted, a manager departing and its greatest recent star on the way to Milan. Messi left that atmosphere, joined friends from his own generation and won. Photographs from Beijing show him beside Sergio Agüero, gold at his chest, the expression unburdened. By then Ronaldinho’s number had become available. Messi wore 10 for the first time in a July friendly at Hibernian; the assignment became official on 3 August. He would return from China to Guardiola, to the number and to a team about to be remade around the qualities that the failed season had exposed most clearly. The space was no longer merely open. It was his.",
    ],
    sources: [
      ["FC Barcelona: 2007–08 annual report", "https://www.fcbarcelona.com/fcbarcelona/document/2025/05/22/86dc0457-85b8-4b73-8122-8de9d022c516/MEM_CLUB_CAS_2007_08.pdf"],
      ["FC Barcelona: Messi’s 2007–08 goals and appearances", "https://www.fcbarcelona.com/en/football/first-team/news/1125678/messi-scores-40-goals-for-the-fifth-consecutive-season"],
      ["UEFA: Messi drives Barça past Lyon", "https://www.uefa.com/uefachampionsleague/news/0254-0d7bbe7788b2-f68e315e5f01-1000/"],
      ["UEFA: Messi scores twice at Celtic", "https://www.uefa.com/uefachampionsleague/news/01ca-0e6f0853ff29-9a41dd45c9e4-1000--two-for-messi-as-barca-see-off-celtic/"],
      ["UEFA: Messi ruled out for six weeks", "https://www.uefa.com/uefachampionsleague/news/01cb-0e6f19d58408-1c237a5b29f1-1000--barca-to-miss-messi-for-last-eight-games/"],
      ["UEFA: Scholes sends United through", "https://www.uefa.com/uefachampionsleague/news/0254-0d7bd506230e-59183c065910-1000--scholes-goal-sends-united-to-moscow/"],
      ["FC Barcelona: Messi inherits the number 10", "https://www.fcbarcelona.com/en/news/792899/a-decade-of-messi-as-barcas-no10"],
      ["FIFA: Messi and Argentina win Olympic gold", "https://inside.fifa.com/en/tournaments/mens/mensolympic/beijing2008/news/messi-and-argentina-grab-gold-in-beijing"],
      ["CAS: FC Barcelona v FIFA Olympic release award", "https://jurisprudence.tas-cas.org/Shared%20Documents/1622%2C%201623%2C%201624.pdf"],
      ["Europa Press: Barcelona permits Messi to remain in Beijing", "https://www.europapress.es/deportes/olimpiadas-00169/noticia-barcelona-no-reclamara-messi-podra-seguir-participando-juegos-olimpicos-20080807153714.html"],
    ],
    photos: [
      {
        after: 4,
        src: "https://editorial.uefa.com/resources/01cb-0e6f19d5757d-cf26d67a5020-1000/lionel_messi_is_helped_off_the_pitch_on_tuesday.jpeg",
        alt: "An injured Lionel Messi leaves the pitch in tears with a Barcelona staff member against Celtic",
        caption: "The same left thigh fails again against Celtic — Camp Nou, 4 March 2008.",
        credit: "Getty Images via UEFA",
        href: "https://www.uefa.com/uefachampionsleague/news/01cb-0e6f19d58408-1c237a5b29f1-1000--barca-to-miss-messi-for-last-eight-games/",
      },
      {
        after: 9,
        src: "https://digitalhub.fifa.com/m/18051ba2593d3919/webimage-o3k4mtza5lr7sozoefdx-jpg.png",
        alt: "Lionel Messi and Sergio Agüero celebrate with their Beijing 2008 Olympic gold medals",
        caption: "A different ending to the summer — Messi and Agüero with Olympic gold in Beijing, 23 August 2008.",
        credit: "FIFA archive",
        href: "https://inside.fifa.com/en/tournaments/mens/mensolympic/beijing2008/news/messi-and-argentina-grab-gold-in-beijing",
      },
    ],
    videos: [
      {
        after: 9,
        youtubeId: "Dqevl3w0_6s",
        title: "Lionel Messi at the Beijing Olympics",
        caption: "The goals, carries and final pass behind Messi’s Beijing gold.",
        credit: "Olympic Games",
        href: "https://www.youtube.com/watch?v=Dqevl3w0_6s",
      },
    ],
  },
};

const filmCatalog = [
  {
    id: "messi-2014",
    title: "Messi",
    year: 2014,
    type: "Film",
    country: "Spain",
    runtime: "1h 33m",
    platform: "Rent / buy",
    focus: "The origin story",
    description:
      "Álex de la Iglesia blends interviews, archive and dramatised childhood scenes.",
    url: "https://www.imdb.com/title/tt3538766/",
  },
  {
    id: "take-ball",
    title: "Take the Ball, Pass the Ball",
    year: 2018,
    type: "Film",
    country: "Spain",
    runtime: "1h 49m",
    platform: "Prime Video",
    focus: "Guardiola’s Barcelona",
    description:
      "The inside story of the side that changed football, with Messi at its centre.",
    url: "https://www.imdb.com/title/tt9135854/",
  },
  {
    id: "barca-dreams",
    title: "Barça Dreams",
    year: 2015,
    type: "Film",
    country: "Spain",
    runtime: "2h",
    platform: "Rent / buy",
    focus: "FC Barcelona",
    description:
      "A sweeping club history from Gamper to Cruyff, Guardiola and Messi.",
    url: "https://www.imdb.com/title/tt4937114/",
  },
  {
    id: "this-is-football",
    title: "This Is Football — Redemption",
    year: 2019,
    type: "Episode",
    country: "UK",
    runtime: "1h",
    platform: "Prime Video",
    focus: "Argentina",
    description:
      "Argentina’s bond with Messi, and the pain and hope behind the shirt.",
    url: "https://www.amazon.co.uk/This-Is-Football-Season-1/dp/B07VQCFJCL",
  },
  {
    id: "forgotten-tape",
    title: "Messi: The Forgotten Tape",
    year: 2026,
    type: "Film",
    country: "Argentina / USA",
    runtime: "24m",
    platform: "Disney+",
    focus: "Choosing Argentina",
    description:
      "The ESPN film uncovers the forgotten tape that helped secure a teenage Messi for Argentina.",
    url: "https://www.disneyplus.com/",
  },
  {
    id: "road-qatar",
    title: "Sean eternos: Campeones de América",
    year: 2022,
    type: "Docuseries",
    country: "Argentina",
    runtime: "3 eps",
    platform: "Netflix",
    focus: "Copa América 2021",
    description:
      "Inside Argentina’s long-awaited triumph and Messi’s release at the Maracanã.",
    url: "https://www.netflix.com/title/81635936",
  },
  {
    id: "destiny",
    title: "Lionel Messi: Destiny",
    year: 2023,
    type: "Film",
    country: "UK",
    runtime: "59m",
    platform: "BBC iPlayer",
    focus: "World Cup 2022",
    description:
      "How Messi completed the one quest that had defined his international career.",
    url: "https://www.bbc.co.uk/iplayer/",
  },
  {
    id: "elijo",
    title: "Elijo creer: El camino del campeón",
    year: 2023,
    type: "Film",
    country: "Argentina",
    runtime: "1h 20m",
    platform: "Max",
    focus: "World Cup 2022",
    description: "The AFA’s official film of Argentina’s road through Qatar.",
    url: "https://www.imdb.com/title/tt30320457/",
  },
  {
    id: "muchachos",
    title: "Muchachos, la película de la gente",
    year: 2023,
    type: "Film",
    country: "Argentina",
    runtime: "1h 40m",
    platform: "Rent / buy",
    focus: "The supporters",
    description:
      "Argentina’s World Cup victory told through the people who lived every second.",
    url: "https://www.imdb.com/title/tt30423047/",
  },
  {
    id: "captains",
    title: "Captains of the World",
    year: 2023,
    type: "Docuseries",
    country: "UK",
    runtime: "6 eps",
    platform: "Netflix",
    focus: "World Cup 2022",
    description:
      "Behind the scenes in Qatar with Messi and the tournament’s other captains.",
    url: "https://www.netflix.com/title/81665981",
  },
  {
    id: "america",
    title: "Messi Meets America",
    year: 2023,
    type: "Docuseries",
    country: "USA",
    runtime: "6 eps",
    platform: "Apple TV+",
    focus: "Inter Miami",
    description:
      "All-access coverage of the arrival that transformed MLS overnight.",
    url: "https://tv.apple.com/show/messi-meets-america/umc.cmc.1jhe8q7x6s7y0mp12f2g9p98n",
  },
  {
    id: "rise",
    title: "Messi’s World Cup: The Rise of a Legend",
    year: 2024,
    type: "Docuseries",
    country: "USA / Argentina",
    runtime: "4 eps",
    platform: "Apple TV+",
    focus: "Argentina career",
    description:
      "Messi narrates five World Cups, from teenage debut to the summit in Qatar.",
    url: "https://tv.apple.com/gb/show/messis-world-cup-the-rise-of-a-legend/umc.cmc.6hpxli71tx1zy1mwz7tutj94h",
  },
  {
    id: "on-side",
    title: "On Side: Major League Soccer",
    year: 2025,
    type: "Docuseries",
    country: "USA",
    runtime: "8 eps",
    platform: "Apple TV+",
    focus: "MLS 2024",
    description:
      "A league-wide all-access series featuring Messi’s first full Miami season.",
    url: "https://tv.apple.com/",
  },
];

const mediaMeta = {
  "messi-2014": ["tt3538766", "7.1"],
  "take-ball": ["tt9135854", "7.9"],
  "barca-dreams": ["tt5001576", "7.3"],
  "this-is-football": ["tt9170224", "8.0"],
  "road-qatar": ["tt23762464", "7.9"],
  destiny: ["tt27881351", "7.7"],
  elijo: ["tt30342692", "7.1"],
  muchachos: ["tt30394627", "8.1"],
  captains: ["tt26218818", "8.3"],
  america: ["tt29373357", "7.0"],
  rise: ["tt27972462", "8.2"],
  "forgotten-tape": ["tt43610307", "6.5"],
  "on-side": ["tt35517757", "7.2"],
};
const trailerIds = {
  "messi-2014": "Ny--3PqxQ1s",
  "take-ball": "VfKls9Eo1ZI",
  "barca-dreams": "jItH5QiEQ9c",
  "this-is-football": "bMrZ-LaOqAY",
  "road-qatar": "zkmxFvWu8Bc",
  destiny: "hA7c_LeAeoU",
  elijo: "-G5cvtQUV14",
  muchachos: "OWmdZZsEfbA",
  captains: "QvbQtARquR8",
  america: "fqRm0TCDRw8",
  rise: "VBItn7fx1EM",
};
export const films = filmCatalog.map((f) => {
  const [imdbId, imdbRating] = mediaMeta[f.id] || [];
  return {
    ...f,
    imdbId,
    imdbRating,
    trailerId: trailerIds[f.id],
    imdbUrl: imdbId
      ? `https://www.imdb.com/title/${imdbId}/`
      : `https://www.imdb.com/find/?q=${encodeURIComponent(f.title)}`,
    poster: imdbId
      ? `https://images.metahub.space/poster/small/${imdbId}/img`
      : null,
  };
});

export const interviews = [
  {
    id: "olga-2023",
    title: "Messi con Migue Granados",
    year: 2023,
    host: "Migue Granados · OLGA",
    language: "Español",
    runtime: "36:52",
    videoId: "qYwlqx-JLok",
    description:
      "At home in Miami: family life, pressure, football and what comes after the game.",
  },
  {
    id: "rac1-2019",
    title: "La entrevista íntegra de RAC1",
    year: 2019,
    host: "RAC1 · Mundo Deportivo",
    language: "Español",
    runtime: "43:04",
    videoId: "WYZq_etlGGE",
    description:
      "A rare, wide-ranging Barcelona-era conversation about the club, family and his future.",
  },
  {
    id: "simplemente-2025",
    title: "Leo Messi en Simplemente Fútbol",
    year: 2025,
    host: "Quique Wolff · Simplemente Fútbol",
    language: "Español",
    runtime: "57:55",
    videoId: "bx242zV3_ME",
    description:
      "Nearly an hour reflecting on his career, teammates, Argentina and his relationship with football.",
  },
  {
    id: "espn-2025",
    title: "Lionel Messi — Full Interview",
    year: 2025,
    host: "ESPN FC",
    language: "Español",
    runtime: "38:19",
    videoId: "D13yNc_dWvQ",
    description:
      "A long-form conversation on Miami, Argentina, the World Cup and the closing chapters of his career.",
  },
  {
    id: "messi-zidane-2023",
    title: "Messi × Zidane: The No. 10 Conversation",
    year: 2023,
    host: "Zinedine Zidane · MARCA / adidas",
    language: "English subtitles",
    runtime: "11:01",
    videoId: "fISJvstEnK8",
    description:
      "Two era-defining number 10s sit down to discuss admiration, Maradona, the shirt and the players who shaped them.",
  },
  {
    id: "tv-publica-2023",
    title: "Leo Messi en Llave a la Eternidad",
    year: 2023,
    host: "Sofi Martínez · Televisión Pública",
    language: "Español",
    runtime: "46:45",
    videoId: "6JYvS4EaVVo",
    description:
      "From painful Argentina defeats to the glory of Qatar, Messi retraces his entire national-team journey.",
  },
  {
    id: "urbana-play-2023",
    title: "Leo Messi mano a mano",
    year: 2023,
    host: "Andy Kusnetzoff · Urbana Play",
    language: "Español",
    runtime: "45:54",
    videoId: "JpAd20of2Jk",
    description:
      "His first long conversation after Qatar: the final, family celebrations and finally becoming world champion.",
  },
  {
    id: "ole-2021",
    title: "Messi íntimo con Olé",
    year: 2021,
    host: "Olé",
    language: "Español",
    runtime: "45:21",
    videoId: "RHqqPNzL0kk",
    description:
      "A personal Barcelona-era conversation about Rosario, Argentina, family, pressure and what makes him suffer.",
  },
  {
    id: "infobae-2024",
    title: "Messi íntimo",
    year: 2024,
    host: "Joaquín Álvarez · Infobae",
    language: "Español",
    runtime: "38:49",
    videoId: "BpY3QPBt5HE",
    description:
      "A relaxed Miami sit-down about his grandmother, family routines, Argentina and why he never rewatched the final.",
  },
];

export const podcasts = [
  {
    id: "zane-lowe-2025",
    title: "Leo Messi",
    show: "The Zane Lowe Interview Series",
    year: 2025,
    language: "English subtitles",
    runtime: "31m",
    platform: "Apple Podcasts",
    videoId: "VC-lJrNaQH4",
    url: "https://podcasts.apple.com/gb/podcast/leo-messi/id1461515071?i=1000696717410",
    description:
      "Soccer’s GOAT opens up about his life on and off the pitch, family, Miami and the next stage of his career.",
  },
  {
    id: "big-time-2024",
    title: "Episode 16: Jean Reno & Lionel Messi",
    show: "Big Time Podcast · Amr Adib & Assala",
    year: 2024,
    language: "Arabic · Spanish",
    runtime: "1h 23m",
    platform: "MBC Shahid",
    url: "https://shahid.mbc.net/en/player/episodes/Big-Time-Podcast-season-1-episode-16/id-1020938",
    description:
      "Jean Reno opens the episode; Messi joins the second segment to recount his journey from Rosario to global stardom.",
  },
];

export const books = [
  {
    id: "balague-en",
    title: "Messi: The Definitive Biography",
    author: "Guillem Balagué",
    year: 2023,
    language: "English",
    kind: "Definitive biography",
    cover:
      "https://www.hachette.co.uk/wp-content/uploads/2023/04/hbg-title-messi-2-76.jpg",
    url: "https://www.amazon.co.uk/dp/1399619136",
  },
  {
    id: "caioli-en",
    title: "Messi: The Inside Story of the Boy Who Became a Legend",
    author: "Luca Caioli",
    year: 2012,
    language: "English",
    kind: "Biography",
    cover: "https://covers.openlibrary.org/b/id/11679411-L.jpg",
    url: "https://www.amazon.co.uk/dp/1906850615",
  },
  {
    id: "faccio-en",
    title: "Messi",
    author: "Leonardo Faccio",
    year: 2012,
    language: "English",
    kind: "Literary portrait",
    cover: "https://covers.openlibrary.org/b/id/7318962-L.jpg",
    url: "https://www.amazon.co.uk/dp/0345802691",
  },
  {
    id: "art-living",
    title: "Lionel Messi and the Art of Living",
    author: "Andy West",
    year: 2018,
    language: "English",
    kind: "Essays · philosophy",
    cover:
      "https://images-na.ssl-images-amazon.com/images/P/1785314505.01.LZZZZZZZ.jpg",
    url: "https://www.amazon.co.uk/dp/1785314505",
  },
  {
    id: "senosiain-es",
    title: "Messi: El genio completo",
    author: "Ariel Senosiain",
    year: 2023,
    language: "Español",
    kind: "Biografía deportiva",
    cover:
      "https://acdn-us.mitiendanube.com/stores/004/088/117/products/690469-311c4b9da2cabca4a817283949508047-640-0.webp",
    url: "https://www.amazon.es/dp/950021220X",
  },
  {
    id: "sottile-es",
    title: "Messi: El distinto",
    author: "Marcelo Sottile",
    year: 2013,
    language: "Español",
    kind: "Biografía · prólogo de Maradona",
    cover:
      "https://acdn-us.mitiendanube.com/stores/746/904/products/d_833729-mla48000097073_102021-o-cf5f17de4486df7f8b16353632348049-640-0.webp",
    url: "https://www.amazon.es/dp/9870725767",
  },
];

// Major honours are assigned to the season in which they were won.
// Individual lists intentionally favour recognised season/tournament awards over monthly prizes and XI selections.
export const honourLedger = {
  "2004–05": {
    team: [
      ["La Liga", "league"],
      ["FIFA U-20 World Cup", "world"],
    ],
    individual: [
      ["U-20 World Cup Golden Ball", "goldball"],
      ["U-20 World Cup Golden Boot", "boot"],
      ["Golden Boy", "ball"],
    ],
  },
  "2005–06": {
    team: [
      ["La Liga", "league"],
      ["UEFA Champions League", "ucl"],
      ["Spanish Super Cup", "supercup"],
    ],
    individual: [["FIFPRO Young Player", "star"]],
  },
  "2006–07": {
    team: [["Spanish Super Cup", "supercup"]],
    individual: [
      ["Bravo Award", "ball"],
      ["FIFPRO Young Player", "star"],
    ],
  },
  "2007–08": {
    team: [],
    individual: [["FIFPRO Young Player", "star"]],
  },
  "2008–09": {
    team: [
      ["La Liga", "league"],
      ["Copa del Rey", "copa"],
      ["UEFA Champions League", "ucl"],
      ["Olympic Gold", "medal"],
    ],
    individual: [
      ["Ballon d’Or", "ball"],
      ["FIFA World Player", "star"],
      ["UEFA Club Forward", "star"],
      ["UCL Top Scorer", "boot"],
      ["La Liga Best Player", "star"],
    ],
  },
  "2009–10": {
    team: [
      ["La Liga", "league"],
      ["Spanish Super Cup", "supercup"],
      ["UEFA Super Cup", "supercup"],
      ["FIFA Club World Cup", "clubworld"],
    ],
    individual: [
      ["FIFA Ballon d’Or", "ball"],
      ["European Golden Shoe", "boot"],
      ["Pichichi Trophy", "pichichi"],
      ["UCL Top Scorer", "boot"],
      ["Club World Cup Golden Ball", "goldball"],
    ],
  },
  "2010–11": {
    team: [
      ["La Liga", "league"],
      ["Spanish Super Cup", "supercup"],
      ["UEFA Champions League", "ucl"],
    ],
    individual: [
      ["FIFA Ballon d’Or", "ball"],
      ["UEFA Best Player in Europe", "star"],
      ["UCL Top Scorer", "boot"],
      ["La Liga Best Player", "star"],
    ],
  },
  "2011–12": {
    team: [
      ["Copa del Rey", "copa"],
      ["Spanish Super Cup", "supercup"],
      ["UEFA Super Cup", "supercup"],
      ["FIFA Club World Cup", "clubworld"],
    ],
    individual: [
      ["FIFA Ballon d’Or", "ball"],
      ["European Golden Shoe", "boot"],
      ["Pichichi Trophy", "pichichi"],
      ["UCL Top Scorer", "boot"],
      ["Club World Cup Golden Ball", "goldball"],
    ],
  },
  "2012–13": {
    team: [["La Liga", "league"]],
    individual: [
      ["European Golden Shoe", "boot"],
      ["Pichichi Trophy", "pichichi"],
      ["La Liga Best Player", "star"],
    ],
  },
  "2013–14": {
    team: [["Spanish Super Cup", "supercup"]],
    individual: [["World Cup Golden Ball", "goldball"]],
  },
  "2014–15": {
    team: [
      ["La Liga", "league"],
      ["Copa del Rey", "copa"],
      ["UEFA Champions League", "ucl"],
    ],
    individual: [
      ["Ballon d’Or", "ball"],
      ["UEFA Best Player in Europe", "star"],
      ["UCL Top Scorer", "boot"],
      ["La Liga Best Player", "star"],
    ],
  },
  "2015–16": {
    team: [
      ["La Liga", "league"],
      ["Copa del Rey", "copa"],
      ["UEFA Super Cup", "supercup"],
      ["FIFA Club World Cup", "clubworld"],
    ],
    individual: [["FIFA Club World Cup Final MVP", "star"]],
  },
  "2016–17": {
    team: [
      ["Copa del Rey", "copa"],
      ["Spanish Super Cup", "supercup"],
    ],
    individual: [
      ["European Golden Shoe", "boot"],
      ["Pichichi Trophy", "pichichi"],
    ],
  },
  "2017–18": {
    team: [
      ["La Liga", "league"],
      ["Copa del Rey", "copa"],
    ],
    individual: [
      ["European Golden Shoe", "boot"],
      ["Pichichi Trophy", "pichichi"],
      ["La Liga Best Player", "star"],
    ],
  },
  "2018–19": {
    team: [
      ["La Liga", "league"],
      ["Spanish Super Cup", "supercup"],
    ],
    individual: [
      ["Ballon d’Or", "ball"],
      ["The Best FIFA Men’s Player", "star"],
      ["European Golden Shoe", "boot"],
      ["Pichichi Trophy", "pichichi"],
      ["UCL Top Scorer", "boot"],
      ["UEFA Forward of the Season", "star"],
    ],
  },
  "2019–20": {
    team: [],
    individual: [
      ["Pichichi Trophy", "pichichi"],
      ["Laureus Sportsman of the Year", "star"],
      ["La Liga Top Assister", "assist"],
    ],
  },
  "2020–21": {
    team: [
      ["Copa del Rey", "copa"],
      ["Copa América", "copa"],
    ],
    individual: [
      ["Ballon d’Or", "ball"],
      ["Copa América Golden Ball", "goldball"],
      ["Copa América Golden Boot", "boot"],
      ["Pichichi Trophy", "pichichi"],
    ],
  },
  "2021–22": {
    team: [
      ["Ligue 1", "league"],
      ["Finalissima", "copa"],
    ],
    individual: [["Finalissima Player of the Match", "star"]],
  },
  "2022–23": {
    team: [
      ["FIFA World Cup", "world"],
      ["Ligue 1", "league"],
      ["Trophée des Champions", "supercup"],
    ],
    individual: [
      ["Ballon d’Or", "ball"],
      ["The Best FIFA Men’s Player", "star"],
      ["World Cup Golden Ball", "goldball"],
      ["Laureus Sportsman of the Year", "star"],
    ],
  },
  2023: {
    team: [["Leagues Cup", "leagues"]],
    individual: [
      ["Leagues Cup Best Player", "star"],
      ["Leagues Cup Top Scorer", "boot"],
      ["TIME Athlete of the Year", "star"],
    ],
  },
  2024: {
    team: [
      ["Supporters’ Shield", "shield"],
      ["Copa América", "copa"],
    ],
    individual: [
      ["Landon Donovan MLS MVP", "mvp"],
      ["MLS Best XI", "star"],
    ],
  },
  2025: {
    team: [
      ["MLS Cup", "mls"],
      ["Eastern Conference", "shield"],
    ],
    individual: [
      ["Landon Donovan MLS MVP", "mvp"],
      ["MLS Golden Boot", "boot"],
      ["MLS Cup MVP", "mvp"],
    ],
  },
  2026: { team: [], individual: [] },
};
