export const seasons = [
  [
    "2004–05",
    "Barcelona",
    "The beginning",
    "Debut at 17. First senior goal, assisted by Ronaldinho.",
    9,
    1,
    0,
    "La Liga",
  ],
  [
    "2005–06",
    "Barcelona",
    "European champion",
    "First Champions League medal and the No. 19 shirt.",
    25,
    8,
    3,
    "Champions League",
  ],
  [
    "2006–07",
    "Barcelona",
    "A star arrives",
    "A Clásico hat-trick and that Getafe goal.",
    36,
    17,
    3,
    "Spanish Super Cup",
  ],
  [
    "2007–08",
    "Barcelona",
    "The new number ten",
    "Olympic gold followed; a changing of the guard at Barça.",
    40,
    16,
    13,
    "—",
  ],
  [
    "2008–09",
    "Barcelona",
    "The treble",
    "Guardiola, Rome and a header no one saw coming.",
    51,
    38,
    17,
    "Treble",
  ],
  [
    "2009–10",
    "Barcelona",
    "First Ballon d’Or",
    "A 47-goal season and the world’s best player crown.",
    53,
    47,
    12,
    "La Liga",
  ],
  [
    "2010–11",
    "Barcelona",
    "Peak Barcelona",
    "Wembley brilliance in one of football’s greatest sides.",
    55,
    53,
    23,
    "Champions League",
  ],
  [
    "2011–12",
    "Barcelona",
    "The 73",
    "A record-breaking club season; four goals in one UCL match.",
    60,
    73,
    29,
    "Copa del Rey",
  ],
  [
    "2012–13",
    "Barcelona",
    "91 in a year",
    "A fourth straight Ballon d’Or and a 100-point league title.",
    50,
    60,
    15,
    "La Liga",
  ],
  [
    "2013–14",
    "Barcelona",
    "The difficult year",
    "Injury interruptions and a World Cup final on the horizon.",
    46,
    41,
    14,
    "Spanish Super Cup",
  ],
  [
    "2014–15",
    "Barcelona",
    "MSN & the treble",
    "That Bayern semi-final, Berlin, and a second treble.",
    57,
    58,
    27,
    "Treble",
  ],
  [
    "2015–16",
    "Barcelona",
    "Domestic double",
    "A fifth Ballon d’Or and another league-and-cup double.",
    49,
    41,
    23,
    "La Liga · Copa del Rey",
  ],
  [
    "2016–17",
    "Barcelona",
    "500 at the Bernabéu",
    "The shirt celebration became an instant icon.",
    52,
    54,
    20,
    "Copa del Rey",
  ],
  [
    "2017–18",
    "Barcelona",
    "Domestic dominance",
    "Unbeaten almost all season; Golden Shoe number five.",
    54,
    45,
    18,
    "La Liga · Copa del Rey",
  ],
  [
    "2018–19",
    "Barcelona",
    "Captain",
    "His first season as captain; the impossible Liverpool free-kick.",
    50,
    51,
    22,
    "La Liga",
  ],
  [
    "2019–20",
    "Barcelona",
    "The assist king",
    "A record 21 league assists in a turbulent season.",
    44,
    31,
    27,
    "—",
  ],
  [
    "2020–21",
    "Barcelona",
    "The farewell season",
    "A last Copa del Rey and finally, Copa América with Argentina.",
    47,
    38,
    14,
    "Copa del Rey · Copa América",
  ],
  [
    "2021–22",
    "Paris Saint-Germain",
    "Paris, year one",
    "A new club after 21 years; league champion in France.",
    34,
    11,
    14,
    "Ligue 1",
  ],
  [
    "2022–23",
    "Paris Saint-Germain",
    "Immortal",
    "Seven goals in Qatar, the World Cup, and an eighth Ballon d’Or.",
    41,
    21,
    20,
    "World Cup · Ligue 1",
  ],
  [
    "2023",
    "Inter Miami",
    "Miami magic",
    "A debut free-kick and seven wins to the club’s first trophy.",
    14,
    11,
    5,
    "Leagues Cup",
  ],
  [
    "2024",
    "Inter Miami",
    "Record breakers",
    "A record MLS regular season and the Supporters’ Shield.",
    25,
    23,
    13,
    "Supporters’ Shield",
  ],
  [
    "2025",
    "Inter Miami",
    "Champions of MLS",
    "A Golden Boot season finished with Miami’s first MLS Cup.",
    null,
    null,
    null,
    "MLS Cup",
  ],
  [
    "2026",
    "Inter Miami",
    "Still writing it",
    "At 39, the captain’s final chapters are being written in real time.",
    null,
    null,
    null,
    "In progress",
  ],
].map((s, i) => ({
  id: i,
  season: s[0],
  club: s[1],
  title: s[2],
  story: s[3],
  apps: s[4],
  goals: s[5],
  assists: s[6],
  honours: s[7],
}));

export const seasonStories = {
  "2004–05": {
    title: "The first light",
    dek: "A borrowed shirt number, nine senior appearances and the little left-footed chip that quietly opened football’s next great age.",
    paragraphs: [
      "There are beginnings that arrive with brass bands, and beginnings that slip into view almost apologetically. Lionel Messi’s first senior season belonged to the latter kind. Barcelona in the summer of 2004 were not waiting for a saviour. For once, they believed they had already found their way. Frank Rijkaard’s first year had ended in a great rush of confidence, Joan Laporta’s presidency had restored ambition, and Ronaldinho had returned delight to a stadium that had spent too many seasons peering anxiously towards Madrid. Samuel Eto’o, Deco, Ludovic Giuly, Juliano Belletti and Henrik Larsson arrived to deepen the revival. Somewhere beneath all that noise was a 17-year-old in the number 30 shirt: slight, watchful, still dividing his days between youth football, Barça B and occasional invitations to train among famous men.",
      "The first hint came in July, in a modest pre-season match at Palamós. Messi scored in a 6–0 victory, an unofficial goal in a fixture that seemed destined to live only in old team sheets and the memories of those who happened to be there. Yet it established the essential grammar early: the low centre of gravity, the ball kept unusually close, the left foot making difficult things appear prearranged. Rijkaard did not hurry him. Barcelona had Giuly on the right, Ronaldinho drifting in from the left and Eto’o attacking the centre with the impatience of a man determined to prove a point. A teenager could be protected inside such abundance. He could watch, learn and wait.",
      "October brought the call. On the 16th, Barcelona crossed the city to Montjuïc for the derby against Espanyol. It was a hard, narrow evening rather than a gala. Deco’s deflected goal had given Barça the lead; Andrés Iniesta had already entered from the bench. With eight minutes remaining, Rijkaard withdrew Deco and sent on Messi. He was 17 years and 114 days old, wearing 30, his hair long and his expression almost stern. There was no goal, no outrageous dribble to announce the future. There were simply a few composed touches in a 1–0 victory and the unmistakable fact of his presence. The senior career had begun in the same Olympic stadium where, nearly two decades later, Barcelona would temporarily make their home.",
      "Eleven days later came a less romantic lesson. Away to third-tier Gramenet in the Copa del Rey, Messi started while many of the established stars were absent. The artificial surface was slick with rain, Barcelona never found their rhythm, and the tie stretched into extra time before Gramenet won 1–0. It was the old cruelty of the cup: pedigree made irrelevant by a single awkward night. For Messi, it was valuable exposure to the unglamorous edge of senior football—the cramped spaces, the heavy challenges, the opponent whose entire season seemed to be concentrated into one evening. Great careers are remembered through finals and floodlights, but they are also educated on nights like Santa Coloma.",
      "By December, Barcelona had already qualified from their Champions League group when Rijkaard took a youthful side to Donetsk. Ronaldinho, Deco and Eto’o were left out; Messi, Joan Verdú and Francisco Peral received their first European starts. Shakhtar won 2–0 through two Julius Aghahowa goals, yet the result has become a footnote to the team sheet. Messi was now a Champions League footballer. He was still physically unfinished and not yet the player who would turn European knockout rounds into his private theatre, but the habits were visible: receiving under pressure, turning towards danger rather than away from it, treating the ball as shelter. Europe did not yet know what had entered the competition.",
      "The winter asked for patience. Barcelona’s season gathered authority through the established constellation around him. Xavi was growing into a freer, more influential midfield role; Deco supplied bite as well as invention; Ronaldinho conducted the mood of the city; Eto’o scored with a forward’s fury. Messi returned repeatedly to the reserves and waited through stretches when a first-team appearance amounted to a late handful of minutes. That waiting matters. Retrospect is tempted to make genius look inevitable, as though the doors simply opened in sequence. In reality, his seven league appearances that season totalled only 77 minutes. He was a possibility being managed, not yet a protagonist.",
      "Spring tightened the title race. Barcelona had led with style, but Real Madrid applied pressure and won April’s Clásico 4–2 at the Bernabéu. Rijkaard’s team could feel six trophyless years pressing against their shoulders. Messi reappeared in the league at Getafe on 17 April and, two weeks later, Albacete came to the Camp Nou. The match was still only 1–0 when he replaced Eto’o late on. Ronaldinho saw the run and lifted a pass over the defence; Messi met it with a left-footed lob so delicate that it seemed to pause above goalkeeper Raúl Valbuena. The flag went up. Offside. Most teenagers might have accepted the warning and chosen something safer next time.",
      "Messi and Ronaldinho simply repeated the idea. Another scooped pass, another dart behind the line, another lob—this one higher, cleaner and legal. The ball fell into the net in stoppage time for 2–0. Messi was 17 years and 311 days old, then Barcelona’s youngest league scorer. What survives most vividly is not merely the finish but the celebration: Ronaldinho bending so the boy could climb onto his back, both of them laughing beneath the Camp Nou lights. It has since acquired the symbolism of a handover, though life is rarely arranged so neatly. Ronaldinho remained the reigning joy of Barcelona. Messi had scored one senior goal. Still, football occasionally composes an image whose meaning grows with every passing year.",
      "A fortnight later, a 1–1 draw at Levante secured Barcelona’s seventeenth league title with two matches remaining—the club’s first championship in six years. Eto’o scored the equaliser; Rijkaard’s collective had completed the restoration. Messi’s statistical contribution was tiny: nine competitive appearances, one goal, scarcely enough playing time to fill a full match in La Liga. Yet the season feels larger than those numbers because every later wonder contains a trace of this first one. The disguised pass from Ronaldinho, the curved run, the refusal to be discouraged by the flag, the left foot lifting the ball beyond a goalkeeper: the vocabulary was already there.",
      "That summer, Messi travelled with Argentina to the World Youth Championship and returned a champion, but that belongs to the threshold of the next chapter. The 2004–05 season should be left where it ended: Barcelona restored to the summit, Ronaldinho smiling, Rijkaard vindicated, and a shy teenager standing just inside the first-team door. Nobody could reasonably have foreseen 778 Barcelona appearances or the mountain of goals and trophies to come. They only knew that the small number 30 made the stadium lean forward. Sometimes that is how history first announces itself—not with certainty, but with curiosity, a murmur spreading around the bowl, and the sense that you had better keep watching.",
    ],
    sources: [
      ["FC Barcelona: Messi’s official debut", "https://www.fcbarcelona.com/en/football/first-team/news/4147765/20-years-since-leo-messis-fc-barcelona-debut"],
      ["UEFA: Champions League debut in Donetsk", "https://www.uefa.com/uefachampionsleague/news/025a-0eaa7d66b33d-3b189c94306f-1000--aghahowa-earns-shakhtar-consolation/"],
      ["FC Barcelona: the first official goal", "https://www.fcbarcelona.com/en/football/first-team/news/4256638/20-years-since-leo-messis-first-official-goal/featured"],
      ["UEFA: Barcelona’s 2004–05 title", "https://www.uefa.com/news-media/news/01a9-0e6cc71410f2-1f8842b7df25-1000--team-ethic-fires-barca-to-glory/"],
    ],
    photos: [
      {
        after: 2,
        src: "https://www.fcbarcelona.com/fcbarcelona/photo/2024/10/12/9251c732-0b4a-4d08-b980-fe7f486fb972/2004-10-16-MESSI-06.JPG",
        alt: "Seventeen-year-old Lionel Messi in Barcelona's 2004–05 shirt during his official debut against Espanyol",
        caption: "The first official steps — Messi enters the Barcelona derby at Montjuïc, 16 October 2004.",
        credit: "FC Barcelona archive",
        href: "https://www.fcbarcelona.com/en/football/first-team/news/4147765/20-years-since-leo-messis-fc-barcelona-debut",
      },
      {
        after: 7,
        src: "https://www.fcbarcelona.com/fcbarcelona/photo/2025/04/30/fb9e1f24-b1c2-463c-9f2b-aa89ca605d13/FCBarcelona-AlbaceteBalompi2-0LligaJornada342004-2005_pic_01-05-05webmessi01.jpg",
        alt: "Lionel Messi celebrates his first official Barcelona goal against Albacete in May 2005",
        caption: "One lob had been disallowed. Messi answered with another — his first official Barcelona goal, 1 May 2005.",
        credit: "FC Barcelona archive",
        href: "https://www.fcbarcelona.com/en/football/first-team/news/4256638/20-years-since-leo-messis-first-official-goal/featured",
      },
    ],
  },
};

const filmCatalog = [
  {
    id: "messi-2014",
    title: "Messi",
    year: 2014,
    type: "Film",
    country: "Spain",
    runtime: "1h 33m",
    platform: "Rent / buy",
    focus: "The origin story",
    description:
      "Álex de la Iglesia blends interviews, archive and dramatised childhood scenes.",
    url: "https://www.imdb.com/title/tt3538766/",
  },
  {
    id: "take-ball",
    title: "Take the Ball, Pass the Ball",
    year: 2018,
    type: "Film",
    country: "Spain",
    runtime: "1h 49m",
    platform: "Prime Video",
    focus: "Guardiola’s Barcelona",
    description:
      "The inside story of the side that changed football, with Messi at its centre.",
    url: "https://www.imdb.com/title/tt9135854/",
  },
  {
    id: "barca-dreams",
    title: "Barça Dreams",
    year: 2015,
    type: "Film",
    country: "Spain",
    runtime: "2h",
    platform: "Rent / buy",
    focus: "FC Barcelona",
    description:
      "A sweeping club history from Gamper to Cruyff, Guardiola and Messi.",
    url: "https://www.imdb.com/title/tt4937114/",
  },
  {
    id: "this-is-football",
    title: "This Is Football — Redemption",
    year: 2019,
    type: "Episode",
    country: "UK",
    runtime: "1h",
    platform: "Prime Video",
    focus: "Argentina",
    description:
      "Argentina’s bond with Messi, and the pain and hope behind the shirt.",
    url: "https://www.amazon.co.uk/This-Is-Football-Season-1/dp/B07VQCFJCL",
  },
  {
    id: "forgotten-tape",
    title: "Messi: The Forgotten Tape",
    year: 2026,
    type: "Film",
    country: "Argentina / USA",
    runtime: "24m",
    platform: "Disney+",
    focus: "Choosing Argentina",
    description:
      "The ESPN film uncovers the forgotten tape that helped secure a teenage Messi for Argentina.",
    url: "https://www.disneyplus.com/",
  },
  {
    id: "road-qatar",
    title: "Sean eternos: Campeones de América",
    year: 2022,
    type: "Docuseries",
    country: "Argentina",
    runtime: "3 eps",
    platform: "Netflix",
    focus: "Copa América 2021",
    description:
      "Inside Argentina’s long-awaited triumph and Messi’s release at the Maracanã.",
    url: "https://www.netflix.com/title/81635936",
  },
  {
    id: "destiny",
    title: "Lionel Messi: Destiny",
    year: 2023,
    type: "Film",
    country: "UK",
    runtime: "59m",
    platform: "BBC iPlayer",
    focus: "World Cup 2022",
    description:
      "How Messi completed the one quest that had defined his international career.",
    url: "https://www.bbc.co.uk/iplayer/",
  },
  {
    id: "elijo",
    title: "Elijo creer: El camino del campeón",
    year: 2023,
    type: "Film",
    country: "Argentina",
    runtime: "1h 20m",
    platform: "Max",
    focus: "World Cup 2022",
    description: "The AFA’s official film of Argentina’s road through Qatar.",
    url: "https://www.imdb.com/title/tt30320457/",
  },
  {
    id: "muchachos",
    title: "Muchachos, la película de la gente",
    year: 2023,
    type: "Film",
    country: "Argentina",
    runtime: "1h 40m",
    platform: "Rent / buy",
    focus: "The supporters",
    description:
      "Argentina’s World Cup victory told through the people who lived every second.",
    url: "https://www.imdb.com/title/tt30423047/",
  },
  {
    id: "captains",
    title: "Captains of the World",
    year: 2023,
    type: "Docuseries",
    country: "UK",
    runtime: "6 eps",
    platform: "Netflix",
    focus: "World Cup 2022",
    description:
      "Behind the scenes in Qatar with Messi and the tournament’s other captains.",
    url: "https://www.netflix.com/title/81665981",
  },
  {
    id: "america",
    title: "Messi Meets America",
    year: 2023,
    type: "Docuseries",
    country: "USA",
    runtime: "6 eps",
    platform: "Apple TV+",
    focus: "Inter Miami",
    description:
      "All-access coverage of the arrival that transformed MLS overnight.",
    url: "https://tv.apple.com/show/messi-meets-america/umc.cmc.1jhe8q7x6s7y0mp12f2g9p98n",
  },
  {
    id: "rise",
    title: "Messi’s World Cup: The Rise of a Legend",
    year: 2024,
    type: "Docuseries",
    country: "USA / Argentina",
    runtime: "4 eps",
    platform: "Apple TV+",
    focus: "Argentina career",
    description:
      "Messi narrates five World Cups, from teenage debut to the summit in Qatar.",
    url: "https://tv.apple.com/gb/show/messis-world-cup-the-rise-of-a-legend/umc.cmc.6hpxli71tx1zy1mwz7tutj94h",
  },
  {
    id: "on-side",
    title: "On Side: Major League Soccer",
    year: 2025,
    type: "Docuseries",
    country: "USA",
    runtime: "8 eps",
    platform: "Apple TV+",
    focus: "MLS 2024",
    description:
      "A league-wide all-access series featuring Messi’s first full Miami season.",
    url: "https://tv.apple.com/",
  },
];

const mediaMeta = {
  "messi-2014": ["tt3538766", "7.1"],
  "take-ball": ["tt9135854", "7.9"],
  "barca-dreams": ["tt5001576", "7.3"],
  "this-is-football": ["tt9170224", "8.0"],
  "road-qatar": ["tt23762464", "7.9"],
  destiny: ["tt27881351", "7.7"],
  elijo: ["tt30342692", "7.1"],
  muchachos: ["tt30394627", "8.1"],
  captains: ["tt26218818", "8.3"],
  america: ["tt29373357", "7.0"],
  rise: ["tt27972462", "8.2"],
  "forgotten-tape": ["tt43610307", "6.5"],
  "on-side": ["tt35517757", "7.2"],
};
const trailerIds = {
  "messi-2014": "Ny--3PqxQ1s",
  "take-ball": "VfKls9Eo1ZI",
  "barca-dreams": "jItH5QiEQ9c",
  "this-is-football": "bMrZ-LaOqAY",
  "road-qatar": "zkmxFvWu8Bc",
  destiny: "hA7c_LeAeoU",
  elijo: "-G5cvtQUV14",
  muchachos: "OWmdZZsEfbA",
  captains: "QvbQtARquR8",
  america: "fqRm0TCDRw8",
  rise: "VBItn7fx1EM",
};
export const films = filmCatalog.map((f) => {
  const [imdbId, imdbRating] = mediaMeta[f.id] || [];
  return {
    ...f,
    imdbId,
    imdbRating,
    trailerId: trailerIds[f.id],
    imdbUrl: imdbId
      ? `https://www.imdb.com/title/${imdbId}/`
      : `https://www.imdb.com/find/?q=${encodeURIComponent(f.title)}`,
    poster: imdbId
      ? `https://images.metahub.space/poster/small/${imdbId}/img`
      : null,
  };
});

export const interviews = [
  {
    id: "olga-2023",
    title: "Messi con Migue Granados",
    year: 2023,
    host: "Migue Granados · OLGA",
    language: "Español",
    runtime: "36:52",
    videoId: "qYwlqx-JLok",
    description:
      "At home in Miami: family life, pressure, football and what comes after the game.",
  },
  {
    id: "rac1-2019",
    title: "La entrevista íntegra de RAC1",
    year: 2019,
    host: "RAC1 · Mundo Deportivo",
    language: "Español",
    runtime: "43:04",
    videoId: "WYZq_etlGGE",
    description:
      "A rare, wide-ranging Barcelona-era conversation about the club, family and his future.",
  },
  {
    id: "simplemente-2025",
    title: "Leo Messi en Simplemente Fútbol",
    year: 2025,
    host: "Quique Wolff · Simplemente Fútbol",
    language: "Español",
    runtime: "57:55",
    videoId: "bx242zV3_ME",
    description:
      "Nearly an hour reflecting on his career, teammates, Argentina and his relationship with football.",
  },
  {
    id: "espn-2025",
    title: "Lionel Messi — Full Interview",
    year: 2025,
    host: "ESPN FC",
    language: "Español",
    runtime: "38:19",
    videoId: "D13yNc_dWvQ",
    description:
      "A long-form conversation on Miami, Argentina, the World Cup and the closing chapters of his career.",
  },
  {
    id: "messi-zidane-2023",
    title: "Messi × Zidane: The No. 10 Conversation",
    year: 2023,
    host: "Zinedine Zidane · MARCA / adidas",
    language: "English subtitles",
    runtime: "11:01",
    videoId: "fISJvstEnK8",
    description:
      "Two era-defining number 10s sit down to discuss admiration, Maradona, the shirt and the players who shaped them.",
  },
  {
    id: "tv-publica-2023",
    title: "Leo Messi en Llave a la Eternidad",
    year: 2023,
    host: "Sofi Martínez · Televisión Pública",
    language: "Español",
    runtime: "46:45",
    videoId: "6JYvS4EaVVo",
    description:
      "From painful Argentina defeats to the glory of Qatar, Messi retraces his entire national-team journey.",
  },
  {
    id: "urbana-play-2023",
    title: "Leo Messi mano a mano",
    year: 2023,
    host: "Andy Kusnetzoff · Urbana Play",
    language: "Español",
    runtime: "45:54",
    videoId: "JpAd20of2Jk",
    description:
      "His first long conversation after Qatar: the final, family celebrations and finally becoming world champion.",
  },
  {
    id: "ole-2021",
    title: "Messi íntimo con Olé",
    year: 2021,
    host: "Olé",
    language: "Español",
    runtime: "45:21",
    videoId: "RHqqPNzL0kk",
    description:
      "A personal Barcelona-era conversation about Rosario, Argentina, family, pressure and what makes him suffer.",
  },
  {
    id: "infobae-2024",
    title: "Messi íntimo",
    year: 2024,
    host: "Joaquín Álvarez · Infobae",
    language: "Español",
    runtime: "38:49",
    videoId: "BpY3QPBt5HE",
    description:
      "A relaxed Miami sit-down about his grandmother, family routines, Argentina and why he never rewatched the final.",
  },
];

export const podcasts = [
  {
    id: "zane-lowe-2025",
    title: "Leo Messi",
    show: "The Zane Lowe Interview Series",
    year: 2025,
    language: "English subtitles",
    runtime: "31m",
    platform: "Apple Podcasts",
    videoId: "VC-lJrNaQH4",
    url: "https://podcasts.apple.com/gb/podcast/leo-messi/id1461515071?i=1000696717410",
    description:
      "Soccer’s GOAT opens up about his life on and off the pitch, family, Miami and the next stage of his career.",
  },
  {
    id: "big-time-2024",
    title: "Episode 16: Jean Reno & Lionel Messi",
    show: "Big Time Podcast · Amr Adib & Assala",
    year: 2024,
    language: "Arabic · Spanish",
    runtime: "1h 23m",
    platform: "MBC Shahid",
    url: "https://shahid.mbc.net/en/player/episodes/Big-Time-Podcast-season-1-episode-16/id-1020938",
    description:
      "Jean Reno opens the episode; Messi joins the second segment to recount his journey from Rosario to global stardom.",
  },
];

export const books = [
  {
    id: "balague-en",
    title: "Messi: The Definitive Biography",
    author: "Guillem Balagué",
    year: 2023,
    language: "English",
    kind: "Definitive biography",
    cover:
      "https://www.hachette.co.uk/wp-content/uploads/2023/04/hbg-title-messi-2-76.jpg",
    url: "https://www.amazon.co.uk/dp/1399619136",
  },
  {
    id: "caioli-en",
    title: "Messi: The Inside Story of the Boy Who Became a Legend",
    author: "Luca Caioli",
    year: 2012,
    language: "English",
    kind: "Biography",
    cover: "https://covers.openlibrary.org/b/id/11679411-L.jpg",
    url: "https://www.amazon.co.uk/dp/1906850615",
  },
  {
    id: "faccio-en",
    title: "Messi",
    author: "Leonardo Faccio",
    year: 2012,
    language: "English",
    kind: "Literary portrait",
    cover: "https://covers.openlibrary.org/b/id/7318962-L.jpg",
    url: "https://www.amazon.co.uk/dp/0345802691",
  },
  {
    id: "art-living",
    title: "Lionel Messi and the Art of Living",
    author: "Andy West",
    year: 2018,
    language: "English",
    kind: "Essays · philosophy",
    cover:
      "https://images-na.ssl-images-amazon.com/images/P/1785314505.01.LZZZZZZZ.jpg",
    url: "https://www.amazon.co.uk/dp/1785314505",
  },
  {
    id: "senosiain-es",
    title: "Messi: El genio completo",
    author: "Ariel Senosiain",
    year: 2023,
    language: "Español",
    kind: "Biografía deportiva",
    cover:
      "https://acdn-us.mitiendanube.com/stores/004/088/117/products/690469-311c4b9da2cabca4a817283949508047-640-0.webp",
    url: "https://www.amazon.es/dp/950021220X",
  },
  {
    id: "sottile-es",
    title: "Messi: El distinto",
    author: "Marcelo Sottile",
    year: 2013,
    language: "Español",
    kind: "Biografía · prólogo de Maradona",
    cover:
      "https://acdn-us.mitiendanube.com/stores/746/904/products/d_833729-mla48000097073_102021-o-cf5f17de4486df7f8b16353632348049-640-0.webp",
    url: "https://www.amazon.es/dp/9870725767",
  },
];

// Major honours are assigned to the season in which they were won.
// Individual lists intentionally favour recognised season/tournament awards over monthly prizes and XI selections.
export const honourLedger = {
  "2004–05": {
    team: [
      ["La Liga", "league"],
      ["FIFA U-20 World Cup", "world"],
    ],
    individual: [
      ["U-20 World Cup Golden Ball", "goldball"],
      ["U-20 World Cup Golden Boot", "boot"],
      ["Golden Boy", "ball"],
    ],
  },
  "2005–06": {
    team: [
      ["La Liga", "league"],
      ["UEFA Champions League", "ucl"],
      ["Spanish Super Cup", "supercup"],
    ],
    individual: [["FIFPRO Young Player", "star"]],
  },
  "2006–07": {
    team: [["Spanish Super Cup", "supercup"]],
    individual: [
      ["Bravo Award", "ball"],
      ["FIFPRO Young Player", "star"],
    ],
  },
  "2007–08": {
    team: [["Olympic Gold", "medal"]],
    individual: [["FIFPRO Young Player", "star"]],
  },
  "2008–09": {
    team: [
      ["La Liga", "league"],
      ["Copa del Rey", "copa"],
      ["UEFA Champions League", "ucl"],
    ],
    individual: [
      ["Ballon d’Or", "ball"],
      ["FIFA World Player", "star"],
      ["UEFA Club Forward", "star"],
      ["UCL Top Scorer", "boot"],
      ["La Liga Best Player", "star"],
    ],
  },
  "2009–10": {
    team: [
      ["La Liga", "league"],
      ["Spanish Super Cup", "supercup"],
      ["UEFA Super Cup", "supercup"],
      ["FIFA Club World Cup", "clubworld"],
    ],
    individual: [
      ["FIFA Ballon d’Or", "ball"],
      ["European Golden Shoe", "boot"],
      ["Pichichi Trophy", "pichichi"],
      ["UCL Top Scorer", "boot"],
      ["Club World Cup Golden Ball", "goldball"],
    ],
  },
  "2010–11": {
    team: [
      ["La Liga", "league"],
      ["Spanish Super Cup", "supercup"],
      ["UEFA Champions League", "ucl"],
    ],
    individual: [
      ["FIFA Ballon d’Or", "ball"],
      ["UEFA Best Player in Europe", "star"],
      ["UCL Top Scorer", "boot"],
      ["La Liga Best Player", "star"],
    ],
  },
  "2011–12": {
    team: [
      ["Copa del Rey", "copa"],
      ["Spanish Super Cup", "supercup"],
      ["UEFA Super Cup", "supercup"],
      ["FIFA Club World Cup", "clubworld"],
    ],
    individual: [
      ["FIFA Ballon d’Or", "ball"],
      ["European Golden Shoe", "boot"],
      ["Pichichi Trophy", "pichichi"],
      ["UCL Top Scorer", "boot"],
      ["Club World Cup Golden Ball", "goldball"],
    ],
  },
  "2012–13": {
    team: [["La Liga", "league"]],
    individual: [
      ["European Golden Shoe", "boot"],
      ["Pichichi Trophy", "pichichi"],
      ["La Liga Best Player", "star"],
    ],
  },
  "2013–14": {
    team: [["Spanish Super Cup", "supercup"]],
    individual: [["World Cup Golden Ball", "goldball"]],
  },
  "2014–15": {
    team: [
      ["La Liga", "league"],
      ["Copa del Rey", "copa"],
      ["UEFA Champions League", "ucl"],
    ],
    individual: [
      ["Ballon d’Or", "ball"],
      ["UEFA Best Player in Europe", "star"],
      ["UCL Top Scorer", "boot"],
      ["La Liga Best Player", "star"],
    ],
  },
  "2015–16": {
    team: [
      ["La Liga", "league"],
      ["Copa del Rey", "copa"],
      ["UEFA Super Cup", "supercup"],
      ["FIFA Club World Cup", "clubworld"],
    ],
    individual: [["FIFA Club World Cup Final MVP", "star"]],
  },
  "2016–17": {
    team: [
      ["Copa del Rey", "copa"],
      ["Spanish Super Cup", "supercup"],
    ],
    individual: [
      ["European Golden Shoe", "boot"],
      ["Pichichi Trophy", "pichichi"],
    ],
  },
  "2017–18": {
    team: [
      ["La Liga", "league"],
      ["Copa del Rey", "copa"],
    ],
    individual: [
      ["European Golden Shoe", "boot"],
      ["Pichichi Trophy", "pichichi"],
      ["La Liga Best Player", "star"],
    ],
  },
  "2018–19": {
    team: [
      ["La Liga", "league"],
      ["Spanish Super Cup", "supercup"],
    ],
    individual: [
      ["Ballon d’Or", "ball"],
      ["The Best FIFA Men’s Player", "star"],
      ["European Golden Shoe", "boot"],
      ["Pichichi Trophy", "pichichi"],
      ["UCL Top Scorer", "boot"],
      ["UEFA Forward of the Season", "star"],
    ],
  },
  "2019–20": {
    team: [],
    individual: [
      ["Pichichi Trophy", "pichichi"],
      ["Laureus Sportsman of the Year", "star"],
      ["La Liga Top Assister", "assist"],
    ],
  },
  "2020–21": {
    team: [
      ["Copa del Rey", "copa"],
      ["Copa América", "copa"],
    ],
    individual: [
      ["Ballon d’Or", "ball"],
      ["Copa América Golden Ball", "goldball"],
      ["Copa América Golden Boot", "boot"],
      ["Pichichi Trophy", "pichichi"],
    ],
  },
  "2021–22": {
    team: [
      ["Ligue 1", "league"],
      ["Finalissima", "copa"],
    ],
    individual: [["Finalissima Player of the Match", "star"]],
  },
  "2022–23": {
    team: [
      ["FIFA World Cup", "world"],
      ["Ligue 1", "league"],
      ["Trophée des Champions", "supercup"],
    ],
    individual: [
      ["Ballon d’Or", "ball"],
      ["The Best FIFA Men’s Player", "star"],
      ["World Cup Golden Ball", "goldball"],
      ["Laureus Sportsman of the Year", "star"],
    ],
  },
  2023: {
    team: [["Leagues Cup", "leagues"]],
    individual: [
      ["Leagues Cup Best Player", "star"],
      ["Leagues Cup Top Scorer", "boot"],
      ["TIME Athlete of the Year", "star"],
    ],
  },
  2024: {
    team: [
      ["Supporters’ Shield", "shield"],
      ["Copa América", "copa"],
    ],
    individual: [
      ["Landon Donovan MLS MVP", "mvp"],
      ["MLS Best XI", "star"],
    ],
  },
  2025: {
    team: [
      ["MLS Cup", "mls"],
      ["Eastern Conference", "shield"],
    ],
    individual: [
      ["Landon Donovan MLS MVP", "mvp"],
      ["MLS Golden Boot", "boot"],
      ["MLS Cup MVP", "mvp"],
    ],
  },
  2026: { team: [], individual: [] },
};
