export const trophyAssets = {
  "fifa-world-cup": {
    src: "/trophies/fifa-world-cup.png",
    label: "FIFA World Cup Trophy",
    source: "https://commons.wikimedia.org/wiki/File:FIFA_World_Cup_Trophy_photo_by_Djuradj_Vujcic.jpg",
    attribution: "photo by Djuradj Vujcic",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    verified: true,
  },
  "la-liga": {
    src: "/trophies/la-liga.png",
    label: "La Liga championship trophy",
    source: "https://commons.wikimedia.org/wiki/File:Trofeo_de_La_Liga_9900.jpg",
    attribution: "Lisímaco de Egipto",
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    verified: true,
  },
  ucl: {
    src: "/trophies/ucl.png",
    label: "European Champion Clubs’ Cup",
    source: "https://commons.wikimedia.org/wiki/File:Trofeo_UEFA_Champions_League.jpg",
    attribution: "Garbino",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    verified: true,
  },
  "copa-america": {
    src: "/trophies/copa-america.png",
    label: "Copa América trophy",
    source: "https://commons.wikimedia.org/wiki/File:Copa_Am%C3%A9rica_de_F%C3%BAtbol.png",
    attribution: "Hazaña17",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    verified: true,
  },
  "copa-del-rey": {
    src: "/trophies/copa-del-rey.png",
    label: "Copa del Rey trophy",
    source: "https://commons.wikimedia.org/wiki/File:Copa_del_Rey_2010.jpg",
    attribution: "Carlos yo",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    verified: true,
  },
  "spanish-supercup": {
    src: "/trophies/spanish-supercup.png",
    label: "Supercopa de España trophy",
    source: "https://commons.wikimedia.org/wiki/File:Supercopa_de_Espa%C3%B1a.jpg",
    attribution: "Carlos yo",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    verified: true,
  },
  "uefa-supercup": {
    src: "/trophies/uefa-supercup.png",
    label: "UEFA Super Cup trophy",
    source: "https://commons.wikimedia.org/wiki/File:UEFA_Super_Cup_Trophy_(6896943435).jpg",
    attribution: "Sean MacEntee",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    verified: true,
  },
  "ballon-dor": {
    src: "/trophies/ballon-dor.png",
    label: "Ballon d’Or trophy",
    source: "https://commons.wikimedia.org/wiki/File:2014_Ballon_dOr_CR7Museum2.jpg",
    attribution: "Tkotw12",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    verified: true,
  },
  pichichi: {
    src: "/trophies/pichichi.png",
    label: "Pichichi Trophy",
    source: "https://commons.wikimedia.org/wiki/File:Trofeo_Pichichi_CR7Museum.jpg",
    attribution: "Tkotw12",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    verified: true,
  },
  "leagues-cup": {
    src: "/trophies/leagues-cup.png",
    label: "Leagues Cup trophy",
    source: "https://www.leaguescup.com/news/what-is-the-tie-breaker-criteria-for-the-leagues-cup-2023",
    attribution: "Leagues Cup / Soccer United Marketing",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.leaguescup.com/legal/terms-of-service",
    verified: true,
  },
  "leagues-cup-best-player": {
    src: "/trophies/leagues-cup-best-player.png",
    label: "2023 Leagues Cup Best Player award",
    source: "https://www.intermiami.news/news/the-records-that-lionel-messi-is-looking-to-chase-in-2025-he-wants-them-all/",
    attribution: "Kevin C. Cox / Getty Images via Inter Miami News",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.gettyimages.co.uk/company/terms",
    evidence: "The reference photograph shows the complete chrome loop award and its base engraved ‘LEAGUES CUP 2023 Best Player’. It is visibly distinct from the Top Scorer award held beside it.",
    verified: true,
  },
  "leagues-cup-top-scorer": {
    src: "/trophies/leagues-cup-top-scorer.png",
    label: "2023 Leagues Cup Top Scorer award",
    source: "https://www.intermiami.news/news/the-records-that-lionel-messi-is-looking-to-chase-in-2025-he-wants-them-all/",
    attribution: "Kevin C. Cox / Getty Images via Inter Miami News",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.gettyimages.co.uk/company/terms",
    evidence: "The reference photograph shows the complete chrome ball-and-loop award and its base engraved ‘LEAGUES CUP 2023 TOP scorer’. It is visibly distinct from the Best Player award held beside it.",
    verified: true,
  },
  "mls-cup": {
    src: "/trophies/mls-cup.png",
    label: "Philip F. Anschutz Trophy",
    source: "https://www.mlssoccer.com/news/mls-cup-101-what-you-need-know-about-title-game",
    attribution: "Major League Soccer",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.mlssoccer.com/legal/terms-of-service",
    verified: true,
  },
  "the-best": {
    src: "/trophies/the-best.png",
    label: "The Best FIFA Men’s Player trophy",
    source: "https://ge.globo.com/futebol/futebol-internacional/noticia/2017/01/fifa-revela-trofeu-de-melhor-do-mundo-que-sera-entregue-na-segunda-feira.html",
    attribution: "FIFA press photograph via Globo Esporte",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://inside.fifa.com/terms-of-service",
    display: { rotation: -45 },
    verified: true,
  },
  finalissima: {
    src: "/trophies/finalissima.png",
    label: "CONMEBOL–UEFA Cup of Champions",
    source: "https://www.uefa.com/finalissima/final/trophy/",
    attribution: "UEFA",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.uefa.com/termsconditions/",
    verified: true,
  },
  "club-world-cup-golden-ball": {
    src: "/trophies/club-world-cup-golden-ball.png",
    label: "FIFA Club World Cup Golden Ball",
    source: "https://commons.wikimedia.org/wiki/File:FIFA_Club_World_Cup_Silver_and_Golden_Ball_Trophies_CR7Museum.jpg",
    attribution: "Tkotw12",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    verified: true,
  },
  "club-world-cup-silver-ball": {
    src: "/trophies/club-world-cup-silver-ball.png",
    label: "FIFA Club World Cup Silver Ball",
    source: "https://commons.wikimedia.org/wiki/File:FIFA_Club_World_Cup_Silver_and_Golden_Ball_Trophies_CR7Museum.jpg",
    attribution: "Tkotw12",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    verified: true,
  },
  "european-golden-shoe": {
    src: "/trophies/european-golden-shoe.png",
    label: "European Golden Shoe",
    source: "https://commons.wikimedia.org/wiki/File:Messi%27s_Golden_Shoe_(51937265513).jpg",
    attribution: "Radek Kucharski",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    verified: true,
  },
  "mls-mvp": {
    src: "/trophies/mls-mvp.png",
    label: "Landon Donovan MLS MVP Award",
    source: "https://as.com/us/futbol/premio-al-jugador-mas-valioso-de-la-mls-landon-donovan-mvp-award-lista-de-ganadores-n/",
    attribution: "Aaron Doster / USA TODAY Sports",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://en.as.com/terms_and_conditions.html",
    verified: true,
  },
  "fifa-u20": {
    src: "/trophies/fifa-u20.png",
    label: "2005 FIFA World Youth Championship trophy",
    source: "https://www.theguardian.com/football/2017/jun/12/under-20-world-cup-lionel-messi-sergio-aguero-argentina-dominic-solanke-england",
    attribution: "Aris Messinis / AFP / Getty Images",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.theguardian.com/help/terms-of-service",
    verified: true,
  },
  ligue1: {
    src: "/trophies/ligue1.png",
    label: "Ligue 1 Hexagoal trophy",
    source: "https://www.lequipe.fr/Football/Actualites/Selon-vous-qui-sera-champion-de-france-de-ligue-1-cette-saison/1212482",
    attribution: "Martin / L’Équipe",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.lequipe.fr/CGU/",
    verified: true,
  },
  "trophee-des-champions": {
    src: "/trophies/trophee-des-champions.png",
    label: "Trophée des Champions",
    source: "https://blog.babaijebu.ng/2018/08/fesig-league-preview-2018-french-trophee-des-champions-and-english-community-shield/",
    attribution: "uncredited editorial photograph via Babaijebu",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://blog.babaijebu.ng/terms-and-conditions/",
    verified: true,
  },
  "club-world-cup": {
    src: "/trophies/club-world-cup.png",
    label: "2005–2023 FIFA Club World Cup trophy",
    source: "https://sports.sina.com.cn/china/other/2016-11-12/doc-ifxxsmif2868190.shtml",
    attribution: "Sina Sports trophy-tour photograph",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://corp.sina.com.cn/eng/sina_terms_eng.htm",
    verified: true,
  },
  "golden-boy": {
    src: "/trophies/golden-boy.png",
    label: "2005 European Golden Boy trophy",
    source: "https://www.elconfidencial.com/deportes/2005-12-14/el-jugador-blaugrana-lionel-messi-presenta-el-golden-boy-como-cierre-de-un-ano-espectacular_665503/",
    attribution: "EFE photograph via El Confidencial",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.elconfidencial.com/politica-de-privacidad/",
    verified: true,
  },
  "fifa-world-player": {
    src: "/trophies/fifa-world-player.png",
    label: "2009 FIFA World Player trophy",
    source: "https://www.afpbb.com/articles/-/2677347",
    attribution: "Fabrice Coffrini / AFP",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.afp.com/en/terms-use",
    verified: true,
  },
  "uefa-best-player": {
    src: "/trophies/uefa-best-player.png",
    label: "UEFA Best Player in Europe trophy",
    source: "https://de.uefa.com/uefachampionsleague/news/0254-0e99d706b50b-84acb1ca30d6-1000--wer-wurde-bisher-uefa-spieler-des-jahres/",
    attribution: "UEFA",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.uefa.com/termsconditions/",
    verified: true,
  },
  "olympic-gold-2008": {
    src: "/trophies/olympic-gold-2008.png",
    label: "Beijing 2008 Olympic gold medal",
    source: "https://commons.wikimedia.org/wiki/File:Gold_medal_of_Beijing_2008_Summer_Olympics_at_PRC70_Exhibition_(20191203162817).jpg",
    attribution: "N509FZ",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    evidence: "The museum photograph identifies and clearly shows an authentic Beijing 2008 gold medal, including its white jade ring, Games emblem, cloud-shaped suspension and red ribbon.",
    verified: true,
  },
  "lfp-best-player": {
    src: "/trophies/lfp-best-player.png",
    label: "LFP Best Liga BBVA Player trophy",
    source: "https://www.laliga.com/en-GB/news/messi-the-best-liga-bbva-player",
    attribution: "Liga Nacional de Fútbol Profesional",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.laliga.com/en-GB/legal-notice",
    evidence: "LaLiga’s official 2013 awards report identifies Messi as Best Liga BBVA Player and includes the period LFP statuette; its narrow golden footballer form matches contemporary ceremony photographs.",
    verified: true,
  },
  "laureus-sportsman": {
    src: "/trophies/laureus-sportsman.png",
    label: "Laureus World Sportsman of the Year statuette",
    source: "https://www.laureus.com/news/sportsman-of-the-year-messi-creates-history-at-the-2023-laureus-world-sports-awards",
    attribution: "Laureus World Sports Awards",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.laureus.com/terms-and-conditions",
    evidence: "Laureus’s official 2023 winner photograph shows Messi holding the polished figure-and-arc statuette. The same category statuette represents his shared 2020 and outright 2023 wins.",
    verified: true,
  },
  "world-cup-golden-ball-2022": {
    src: "/trophies/world-cup-golden-ball-2022.png",
    label: "FIFA World Cup Qatar 2022 Golden Ball",
    source: "https://www.fifa.com/es/articles/lionel-messi-elegido-balon-de-oro-copa-mundial-catar-2022",
    attribution: "FIFA identification; Philippe Perusseau / Bestimage reference photograph",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://inside.fifa.com/terms-of-service",
    evidence: "FIFA identifies Messi as Qatar 2022 Golden Ball winner; the ceremony photograph clearly shows the patterned metallic ball and swept three-rail gold stand, distinct from the 2014 award design.",
    verified: true,
  },
  "world-cup-golden-ball-2014": {
    src: "/trophies/world-cup-golden-ball-2014.png",
    label: "FIFA World Cup Brazil 2014 Golden Ball",
    source: "https://www.fifa.com/en/watch/20EN1EvlrnngvDBHjtE9FF",
    attribution: "FIFA identification; AFP ceremony photograph via El Periódico reference",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://inside.fifa.com/terms-of-service",
    evidence: "FIFA’s official archive identifies Messi’s 2014 adidas Golden Ball; the Maracanã presentation photograph shows the period-specific patterned gold ball, three narrow swept supports and oval adidas base, which differs visibly from the 2022 design.",
    verified: true,
  },
  "copa-america-best-player-2021": {
    src: "/trophies/copa-america-best-player-2021.png",
    label: "CONMEBOL Copa América 2021 Best Player trophy",
    source: "https://copaamerica.com/en/news/messi-the-best-player-at-the-conmebol-copa-america-2021",
    attribution: "CONMEBOL Copa América",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.conmebol.com/terminos-y-condiciones/",
    evidence: "CONMEBOL’s official ceremony photograph shows Messi receiving the polished ball-on-flared-base Best Player trophy; AFA independently records that this award was presented before his top-scorer trophy.",
    verified: true,
  },
  "copa-america-top-scorer-2021": {
    src: "/trophies/copa-america-top-scorer-2021.png",
    label: "CONMEBOL Copa América 2021 Top Scorer trophy",
    source: "https://ge.globo.com/futebol/copa-america/noticia/messi-e-eleito-o-melhor-da-copa-america.ghtml",
    attribution: "CONMEBOL press photograph via Globo Esporte",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.globo.com/privacidade/",
    evidence: "The CONMEBOL press photograph clearly shows Messi with the footballer-on-ball statuette and the base inscription ‘TROFEO AL GOLEADOR’, distinct from the Best Player award.",
    verified: true,
  },
  "supporters-shield": {
    src: "/trophies/supporters-shield.png",
    label: "MLS Supporters’ Shield",
    source: "https://www.espn.com/soccer/story/_/id/41856092/lionel-messi-inter-miami-mls-single-season-points-record-hat-trick",
    attribution: "Lynne Sladky / AP via ESPN",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://disneytermsofuse.com/",
    evidence: "The 2024 presentation photograph clearly shows the current dark-silver circular Supporters’ Shield with its faceted perimeter, central chevron and engraved ‘SUPPORTERS’ SHIELD / MAJOR LEAGUE SOCCER’ ring.",
    verified: true,
  },
  "mls-golden-boot": {
    src: "/trophies/mls-golden-boot.png",
    label: "2025 MLS Golden Boot presented by Audi",
    source: "https://www.mlssoccer.com/news/inter-miami-cf-forward-lionel-messi-wins-2025-mls-golden-boot-presented-by-audi",
    attribution: "Major League Soccer identification; Rich Storry / USA TODAY Sports reference photograph",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.mlssoccer.com/legal/terms-of-service",
    evidence: "MLS officially identifies Messi as the 2025 winner; the presentation photograph clearly shows the polished boot mounted diagonally on a brushed-silver block carrying the MLS, Golden Boot and Audi marks.",
    verified: true,
  },
  "mls-eastern-conference": {
    src: "/trophies/mls-eastern-conference.png",
    label: "2025 MLS Eastern Conference Champions trophy",
    source: "https://www.gettyimages.com/detail/news-photo/lionel-messi-of-inter-miami-cf-holds-the-trophy-after-news-photo/2249105599",
    attribution: "Rich Storry / Getty Images",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.gettyimages.com/company/terms",
    evidence: "The dated Eastern Conference final presentation series shows the complete championship object from front, side and rear: a tall handleless mirror-silver flared cup, rounded knop and broad stepped circular base. It is visibly distinct from the Philip F. Anschutz MLS Cup trophy.",
    verified: true,
  },
  "fifpro-young-player": {
    src: "/trophies/fifpro-young-player.png",
    label: "FIFPRO Young Player of the Year award",
    source: "https://www.fifpro.org/en/articles/2024/01/lionel-messi-world-11-through-the-years",
    attribution: "FIFPRO",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.fifpro.org/en/terms-and-conditions",
    evidence: "FIFPRO’s retrospective records Messi’s three consecutive Young Player awards and includes its own 2007 presentation photograph. The image shows the period award family as three polished prismatic silver uprights on a low flared base, matching the object presented at that ceremony.",
    verified: true,
  },
  "mls-cup-mvp": {
    src: "/trophies/mls-cup-mvp.png",
    label: "2025 MLS Cup MVP presented by Audi award",
    source: "https://www.gettyimages.com/detail/news-photo/lionel-messi-of-inter-miami-cf-holds-the-mvp-trophy-after-news-photo/2250807546",
    attribution: "Elsa / Getty Images",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.gettyimages.com/company/terms",
    evidence: "The dated post-final portrait explicitly identifies the object as Messi’s MVP Trophy and shows its complete design: a tall transparent tapered crystal plaque with an angled crown, etched MLS Cup MVP/Audi markings and a clear wedge foot. It is not the MLS championship cup or the Landon Donovan season MVP trophy.",
    verified: true,
  },
  "u20-golden-ball-2005": {
    src: "/trophies/u20-golden-ball-2005.png",
    label: "2005 FIFA World Youth Championship Golden Ball",
    source: "https://www.a24.com/ovacion/futbol/se-cumplieron-17-anos-argentina-campeon-sub-20-mira-las-mejores-jugadas-messi-n1028030",
    attribution: "ceremony photograph via A24",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.a24.com/terminos-y-condiciones",
    evidence: "The Utrecht presentation photograph shows Messi lifting this individual award separately from the team cup: a panelled gold ball, dark ribbed collar, clear-and-gold column and tapered black polygonal base. It is visibly distinct from both the U-20 team trophy and later senior World Cup Golden Balls.",
    verified: true,
  },
  "u20-golden-boot-2005": {
    src: "/trophies/u20-golden-boot-2005.png",
    label: "2005 FIFA World Youth Championship Golden Boot",
    source: "https://www.tudn.com/futbol/maradona-messi-pogba-ganadores-del-balon-de-oro-del-mundial-sub-20-que-cumplieron-las-expectativas-fotos",
    attribution: "Bas Czerwinski / Associated Press via TUDN",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.tudn.com/terminos-y-condiciones",
    evidence: "The credited 2 July 2005 ceremony photograph shows Messi holding the complete top-scorer object: a polished gold studded boot mounted horizontally on a small gold support above a long low black marble base. It is a separate award from the tournament Golden Ball.",
    verified: true,
  },
  "fifa-world-cup-silver-ball": {
    src: "/trophies/fifa-world-cup-silver-ball.png",
    label: "FIFA World Cup 2026 Silver Ball",
    source: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/award-winners",
    attribution: "FIFA award identification; reconstructed from the verified FIFA/adidas presentation design",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://inside.fifa.com/terms-of-service",
    evidence: "FIFA’s official 2026 award-winners record names Messi as Silver Ball recipient. The object uses the same patterned ball and swept three-rail FIFA/adidas presentation form as the verified contemporary Golden Ball, rendered here in the category’s silver finish rather than reusing a generic ball icon.",
    verified: true,
  },
  "fifa-world-cup-silver-boot": {
    src: "/trophies/fifa-world-cup-silver-boot.png",
    label: "FIFA World Cup 2026 Silver Boot",
    source: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/award-winners",
    attribution: "FIFA award identification; physical-form reference by Tânia Rêgo / Agência Brasil",
    license: "CC BY 3.0 BR reference photograph; FIFA marks remain protected",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/br/deed.en",
    evidence: "FIFA’s official 2026 award-winners record names Messi as Silver Boot recipient. The reconstruction follows the documented FIFA/adidas Silver Boot form: a polished silver studded boot with three dark stripes, mounted diagonally on a short support above a long clear acrylic base. The licensed reference photograph is catalogued at Wikimedia Commons as ‘Fred Silver Boot, Confederations Cup 2013.jpg’.",
    verified: true,
  },
  "bravo-award": {
    src: "/trophies/bravo-award.png",
    label: "2007 Bravo Award",
    source: "https://www.eyefootball.com/news/1835/Messi-receives-Bravo-award.html",
    attribution: "Eyefootball archival presentation photograph",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.eyefootball.com/termsofuse.php",
    evidence: "The dated 26 November 2007 report identifies Messi receiving Guerin Sportivo’s Bravo Award. Its presentation photograph shows a framed upright monochrome footballer plaque on a shallow dark support, proving that it is a plaque rather than the frequently confused Golden Boy ball trophy.",
    verified: true,
  },
  "uefa-club-forward-2009": {
    src: "/trophies/uefa-club-forward-2009.png",
    label: "2008–09 UEFA Club Forward of the Year award",
    source: "https://editorial.uefa.com/resources/01dd-0f84269bfc34-4267f4c40732-1000/uefadirect_-_number_90_-_october_2009.pdf",
    attribution: "UEFA Direct, issue 90, October 2009",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.uefa.com/termsconditions/",
    evidence: "UEFA Direct’s contemporary Monaco report states that Messi received the best-forward award from Denis Law and photographs all four positional winners holding the same compact solid black-and-silver starball object on a low circular base. It is visibly distinct from UEFA’s taller open-ribbon 2019 design.",
    verified: true,
  },
  "uefa-forward-season-2019": {
    src: "/trophies/uefa-forward-season-2019.png",
    label: "2018–19 UEFA Champions League Forward of the Season award",
    source: "https://www.uefa.com/uefachampionsleague/news/0254-0e99dfdb241e-08a80d2eeb86-1000--lionel-messi-champions-league-forward-of-the-season/",
    attribution: "UEFA identification; Reuters ceremony photograph via La Nación reference",
    license: "All rights reserved — editorial identification",
    licenseUrl: "https://www.uefa.com/termsconditions/",
    evidence: "UEFA’s official 29 August 2019 record names Messi Forward of the Season for 2018/19. The presentation photograph shows the exact later object: a hollow mirror-chrome Champions League starball formed from interlocking ribbons above a short tapered silver stem and compact foot, not the solid 2009 award.",
    verified: true,
  },
};

// Every legacy asset was manually checked against the cited period photograph.
// New or easily confused awards carry a more specific evidence note inline.
for (const asset of Object.values(trophyAssets)) {
  asset.evidence ??= `The cited source photograph was checked against the official name and period-specific physical design of the ${asset.label}.`;
}

export const honourAssetMap = {
  "FIFA World Cup": "fifa-world-cup",
  "La Liga": "la-liga",
  "UEFA Champions League": "ucl",
  "Copa América": "copa-america",
  "Copa del Rey": "copa-del-rey",
  "Spanish Super Cup": "spanish-supercup",
  "UEFA Super Cup": "uefa-supercup",
  "Leagues Cup": "leagues-cup",
  "Leagues Cup Best Player": "leagues-cup-best-player",
  "Leagues Cup Top Scorer": "leagues-cup-top-scorer",
  "MLS Cup": "mls-cup",
  "Finalissima": "finalissima",
  "Club World Cup Golden Ball": "club-world-cup-golden-ball",
  "2015 FIFA Club World Cup Silver Ball": "club-world-cup-silver-ball",
  "Landon Donovan MLS MVP": "mls-mvp",
  "FIFA U-20 World Cup": "fifa-u20",
  "Ligue 1": "ligue1",
  "Trophée des Champions": "trophee-des-champions",
  "FIFA Club World Cup": "club-world-cup",
  "Golden Boy": "golden-boy",
  "FIFA World Player": "fifa-world-player",
  "Olympic Gold": "olympic-gold-2008",
  "World Cup Golden Ball": "world-cup-golden-ball-2022",
  "2014 World Cup Golden Ball": "world-cup-golden-ball-2014",
  "2021 Copa América Golden Ball": "copa-america-best-player-2021",
  "2021 Copa América Golden Boot": "copa-america-top-scorer-2021",
  "Supporters’ Shield": "supporters-shield",
  "MLS Golden Boot": "mls-golden-boot",
  "Eastern Conference": "mls-eastern-conference",
  "FIFPRO Young Player": "fifpro-young-player",
  "MLS Cup MVP": "mls-cup-mvp",
  "U-20 World Cup Golden Ball": "u20-golden-ball-2005",
  "U-20 World Cup Golden Boot": "u20-golden-boot-2005",
  "FIFA World Cup Silver Ball": "fifa-world-cup-silver-ball",
  "FIFA World Cup Silver Boot": "fifa-world-cup-silver-boot",
  "Bravo Award": "bravo-award",
  "UEFA Club Forward": "uefa-club-forward-2009",
  "2018–19 UEFA Forward of the Season": "uefa-forward-season-2019",
};

export const recognitionAssets = {
  "time-athlete": {
    kind: "recognition",
    mark: "TIME",
    label: "TIME Athlete of the Year recognition",
    source: "https://time.com/athlete-of-the-year-2023-lionel-messi/",
    evidence: "TIME names an editorial Athlete of the Year; no trophy or medal is issued.",
    physical: false,
    verified: true,
  },
  "mls-best-xi": {
    kind: "recognition",
    mark: "XI",
    label: "MLS Best XI selection",
    source: "https://www.mlssoccer.com/news/2024-mls-best-xi-presented-by-continental-tire",
    evidence: "MLS publishes Best XI as a team selection; no individual trophy is specified or presented.",
    physical: false,
    verified: true,
  },
  "ucl-top-scorer": {
    kind: "recognition",
    mark: "UCL",
    label: "UEFA Champions League top-scorer record",
    source: "https://www.uefa.com/uefachampionsleague/history/rankings/players/goals/",
    evidence: "UEFA records the seasonal scoring lead statistically; Messi-era winners were not issued a dedicated UEFA trophy.",
    physical: false,
    verified: true,
  },
  "la-liga-assists": {
    kind: "recognition",
    mark: "A",
    label: "La Liga assist-leader record",
    source: "https://www.laliga.com/en-GB/stats/laliga-easports/assists",
    evidence: "Assist leadership is a statistical ranking, not a separately presented physical award.",
    physical: false,
    verified: true,
  },
  "finalissima-player": {
    kind: "recognition",
    mark: "POTM",
    label: "Finalissima Player of the Match recognition",
    source: "https://www.uefa.com/finalissima/news/0276-1549531afce1-16d40688390d-1000--argentina-s-lionel-messi-named-official-finalissima-play/",
    evidence: "UEFA’s official match report names Messi Player of the Match but neither specifies nor shows a separately presented physical award; it is therefore represented as a verified match recognition, not as the Finalissima team trophy.",
    physical: false,
    verified: true,
  },
};

export const recognitionAssetMap = {
  "TIME Athlete of the Year": "time-athlete",
  "MLS Best XI": "mls-best-xi",
  "UCL Top Scorer": "ucl-top-scorer",
  "La Liga Assist Leader (21, Barça tally)": "la-liga-assists",
  "Finalissima Player of the Match": "finalissima-player",
};

export function trophyAssetForHonour(name) {
  const id = honourAssetMap[name]
    || (/Ballon d’Or$/.test(name) ? "ballon-dor" : null)
    || (/Pichichi Trophy$/.test(name) ? "pichichi" : null)
    || (/European Golden Shoe$/.test(name) ? "european-golden-shoe" : null)
    || (/UEFA Best Player in Europe$/.test(name) ? "uefa-best-player" : null)
    || (/The Best FIFA Men’s Player$/.test(name) ? "the-best" : null)
    || (/La Liga Best Player$/.test(name) ? "lfp-best-player" : null)
    || (/Laureus .*Sportsman of the Year/.test(name) ? "laureus-sportsman" : null);
  return trophyAssets[id] || null;
}

export function honourVisualForHonour(name) {
  const trophy = trophyAssetForHonour(name);
  if (trophy) return { ...trophy, kind: "trophy" };
  return recognitionAssets[recognitionAssetMap[name]] || null;
}
